/**
 * Target Schema and Synonyms
 *
 * Defines the target database schema and column name synonyms
 * for intelligent field mapping.
 */

import type { DataPattern } from './types';

/**
 * Target schema knowledge - Maps tables to columns with acceptable patterns
 */
export const TARGET_SCHEMA: Record<string, Record<string, DataPattern[]>> = {
  hc_staff: {
    staff_id: ['ID_UUID'],
    employee_id: ['ID_NUMERIC', 'ID_ALPHANUMERIC'],
    first_name: ['NAME_FIRST', 'TEXT_SHORT'],
    middle_name: ['NAME_FIRST', 'TEXT_SHORT'],
    last_name: ['NAME_LAST', 'TEXT_SHORT'],
    suffix: ['CODE', 'TEXT_SHORT'],
    preferred_name: ['NAME_FIRST', 'TEXT_SHORT'],
    email: ['EMAIL'],
    phone_work: ['PHONE'],
    phone_mobile: ['PHONE'],
    phone_home: ['PHONE'],
    npi: ['NPI'],
    dea_number: ['ID_ALPHANUMERIC'],
    upin: ['ID_ALPHANUMERIC'],
    medicare_ptan: ['ID_ALPHANUMERIC'],
    medicaid_id: ['ID_ALPHANUMERIC'],
    hire_date: ['DATE', 'DATE_ISO'],
    termination_date: ['DATE', 'DATE_ISO'],
    date_of_birth: ['DATE', 'DATE_ISO'],
    gender: ['CODE', 'TEXT_SHORT'],
    employment_status: ['CODE'],
    employment_type: ['CODE'],
    address_line1: ['TEXT_SHORT'],
    address_line2: ['TEXT_SHORT'],
    city: ['TEXT_SHORT'],
    state: ['STATE_CODE'],
    zip: ['ZIP'],
    source_system: ['CODE', 'TEXT_SHORT'],
    source_id: ['ID_ALPHANUMERIC', 'ID_NUMERIC'],
  },
  hc_staff_license: {
    license_number: ['ID_ALPHANUMERIC'],
    state: ['STATE_CODE'],
    issued_date: ['DATE', 'DATE_ISO'],
    expiration_date: ['DATE', 'DATE_ISO'],
    verification_status: ['CODE'],
  },
  hc_staff_credential: {
    credential_number: ['ID_ALPHANUMERIC'],
    issued_date: ['DATE', 'DATE_ISO'],
    expiration_date: ['DATE', 'DATE_ISO'],
    issuing_institution: ['TEXT_SHORT'],
    verification_status: ['CODE'],
  },
  hc_department: {
    department_code: ['CODE', 'ID_ALPHANUMERIC'],
    department_name: ['TEXT_SHORT'],
    department_type: ['CODE'],
    cost_center: ['ID_ALPHANUMERIC'],
    location: ['TEXT_SHORT'],
  },
  hc_facility: {
    facility_code: ['CODE', 'ID_ALPHANUMERIC'],
    facility_name: ['TEXT_SHORT'],
    facility_type: ['CODE'],
    address_line1: ['TEXT_SHORT'],
    address_line2: ['TEXT_SHORT'],
    city: ['TEXT_SHORT'],
    state: ['STATE_CODE'],
    zip: ['ZIP'],
    phone: ['PHONE'],
    fax: ['PHONE'],
  },
  hc_organization: {
    organization_name: ['TEXT_SHORT'],
    organization_type: ['CODE'],
    npi: ['NPI'],
    tax_id: ['ID_ALPHANUMERIC'],
    address_line1: ['TEXT_SHORT'],
    city: ['TEXT_SHORT'],
    state: ['STATE_CODE'],
    zip: ['ZIP'],
    phone: ['PHONE'],
    cms_certification_number: ['ID_ALPHANUMERIC'],
  },

  // FHIR R4 Clinical Resources
  fhir_patient: {
    resource_id: ['ID_UUID', 'FHIR_REFERENCE'],
    resource_type: ['FHIR_RESOURCE_TYPE'],
    identifier_mrn: ['ID_ALPHANUMERIC', 'ID_NUMERIC'],
    identifier_ssn: ['SSN'],
    name_given: ['NAME_FIRST', 'TEXT_SHORT'],
    name_family: ['NAME_LAST', 'TEXT_SHORT'],
    name_prefix: ['CODE', 'TEXT_SHORT'],
    name_suffix: ['CODE', 'TEXT_SHORT'],
    birth_date: ['DATE', 'DATE_ISO'],
    gender: ['CODE'],
    deceased_boolean: ['BOOLEAN'],
    deceased_datetime: ['DATE_ISO'],
    address_line: ['TEXT_SHORT'],
    address_city: ['TEXT_SHORT'],
    address_state: ['STATE_CODE'],
    address_postal_code: ['ZIP'],
    telecom_phone: ['PHONE'],
    telecom_email: ['EMAIL'],
    marital_status: ['CODE'],
    language: ['CODE'],
  },
  fhir_observation: {
    resource_id: ['ID_UUID', 'FHIR_REFERENCE'],
    resource_type: ['FHIR_RESOURCE_TYPE'],
    status: ['CODE'],
    category: ['LOINC', 'SNOMED_CT', 'CODE'],
    code_loinc: ['LOINC'],
    code_snomed: ['SNOMED_CT'],
    code_display: ['TEXT_SHORT'],
    subject: ['FHIR_REFERENCE'],
    encounter: ['FHIR_REFERENCE'],
    effective_datetime: ['DATE_ISO'],
    value_quantity: ['ID_NUMERIC', 'CURRENCY'],
    value_quantity_unit: ['CODE', 'TEXT_SHORT'],
    value_string: ['TEXT_SHORT', 'TEXT_LONG'],
    value_boolean: ['BOOLEAN'],
    interpretation: ['CODE'],
    reference_range_low: ['ID_NUMERIC'],
    reference_range_high: ['ID_NUMERIC'],
    performer: ['FHIR_REFERENCE'],
    note: ['TEXT_LONG'],
  },
  fhir_condition: {
    resource_id: ['ID_UUID', 'FHIR_REFERENCE'],
    resource_type: ['FHIR_RESOURCE_TYPE'],
    clinical_status: ['CODE'],
    verification_status: ['CODE'],
    category: ['SNOMED_CT', 'CODE'],
    severity: ['SNOMED_CT', 'CODE'],
    code_icd10: ['ICD10'],
    code_snomed: ['SNOMED_CT'],
    code_display: ['TEXT_SHORT'],
    body_site: ['SNOMED_CT', 'CODE'],
    subject: ['FHIR_REFERENCE'],
    encounter: ['FHIR_REFERENCE'],
    onset_datetime: ['DATE_ISO'],
    onset_age: ['ID_NUMERIC'],
    onset_string: ['TEXT_SHORT'],
    abatement_datetime: ['DATE_ISO'],
    recorded_date: ['DATE_ISO'],
    recorder: ['FHIR_REFERENCE'],
    asserter: ['FHIR_REFERENCE'],
    note: ['TEXT_LONG'],
  },
  fhir_medication_request: {
    resource_id: ['ID_UUID', 'FHIR_REFERENCE'],
    resource_type: ['FHIR_RESOURCE_TYPE'],
    status: ['CODE'],
    status_reason: ['CODE'],
    intent: ['CODE'],
    category: ['CODE'],
    priority: ['CODE'],
    medication_rxnorm: ['RXNORM'],
    medication_ndc: ['NDC'],
    medication_display: ['TEXT_SHORT'],
    subject: ['FHIR_REFERENCE'],
    encounter: ['FHIR_REFERENCE'],
    authored_on: ['DATE_ISO'],
    requester: ['FHIR_REFERENCE'],
    performer: ['FHIR_REFERENCE'],
    reason_code: ['SNOMED_CT', 'ICD10', 'CODE'],
    reason_reference: ['FHIR_REFERENCE'],
    dosage_text: ['TEXT_SHORT', 'TEXT_LONG'],
    dosage_route: ['SNOMED_CT', 'CODE'],
    dosage_dose_quantity: ['ID_NUMERIC'],
    dosage_dose_unit: ['CODE', 'TEXT_SHORT'],
    dispense_quantity: ['ID_NUMERIC'],
    dispense_unit: ['CODE', 'TEXT_SHORT'],
    days_supply: ['ID_NUMERIC'],
    number_of_refills: ['ID_NUMERIC'],
    substitution_allowed: ['BOOLEAN'],
    note: ['TEXT_LONG'],
  },
  fhir_procedure: {
    resource_id: ['ID_UUID', 'FHIR_REFERENCE'],
    resource_type: ['FHIR_RESOURCE_TYPE'],
    status: ['CODE'],
    status_reason: ['CODE'],
    category: ['SNOMED_CT', 'CODE'],
    code_cpt: ['CPT'],
    code_snomed: ['SNOMED_CT'],
    code_display: ['TEXT_SHORT'],
    subject: ['FHIR_REFERENCE'],
    encounter: ['FHIR_REFERENCE'],
    performed_datetime: ['DATE_ISO'],
    performed_period_start: ['DATE_ISO'],
    performed_period_end: ['DATE_ISO'],
    recorder: ['FHIR_REFERENCE'],
    asserter: ['FHIR_REFERENCE'],
    performer: ['FHIR_REFERENCE'],
    performer_role: ['CODE'],
    location: ['FHIR_REFERENCE'],
    reason_code: ['SNOMED_CT', 'ICD10', 'CODE'],
    reason_reference: ['FHIR_REFERENCE'],
    body_site: ['SNOMED_CT', 'CODE'],
    outcome: ['SNOMED_CT', 'CODE'],
    complication: ['SNOMED_CT', 'ICD10', 'CODE'],
    follow_up: ['SNOMED_CT', 'CODE'],
    note: ['TEXT_LONG'],
    used_reference: ['FHIR_REFERENCE'],
  },
  fhir_encounter: {
    resource_id: ['ID_UUID', 'FHIR_REFERENCE'],
    resource_type: ['FHIR_RESOURCE_TYPE'],
    status: ['CODE'],
    status_history: ['CODE'],
    class_code: ['CODE'],
    type: ['SNOMED_CT', 'CPT', 'CODE'],
    service_type: ['SNOMED_CT', 'CODE'],
    priority: ['SNOMED_CT', 'CODE'],
    subject: ['FHIR_REFERENCE'],
    participant: ['FHIR_REFERENCE'],
    participant_type: ['CODE'],
    period_start: ['DATE_ISO'],
    period_end: ['DATE_ISO'],
    length_value: ['ID_NUMERIC'],
    length_unit: ['CODE'],
    reason_code: ['SNOMED_CT', 'ICD10', 'CODE'],
    reason_reference: ['FHIR_REFERENCE'],
    diagnosis: ['FHIR_REFERENCE'],
    diagnosis_use: ['CODE'],
    diagnosis_rank: ['ID_NUMERIC'],
    account: ['FHIR_REFERENCE'],
    hospitalization_admit_source: ['CODE'],
    hospitalization_discharge_disposition: ['CODE'],
    location: ['FHIR_REFERENCE'],
    service_provider: ['FHIR_REFERENCE'],
    part_of: ['FHIR_REFERENCE'],
  },
  fhir_diagnostic_report: {
    resource_id: ['ID_UUID', 'FHIR_REFERENCE'],
    resource_type: ['FHIR_RESOURCE_TYPE'],
    status: ['CODE'],
    category: ['LOINC', 'SNOMED_CT', 'CODE'],
    code_loinc: ['LOINC'],
    code_snomed: ['SNOMED_CT'],
    code_display: ['TEXT_SHORT'],
    subject: ['FHIR_REFERENCE'],
    encounter: ['FHIR_REFERENCE'],
    effective_datetime: ['DATE_ISO'],
    effective_period_start: ['DATE_ISO'],
    effective_period_end: ['DATE_ISO'],
    issued: ['DATE_ISO'],
    performer: ['FHIR_REFERENCE'],
    results_interpreter: ['FHIR_REFERENCE'],
    specimen: ['FHIR_REFERENCE'],
    result: ['FHIR_REFERENCE'],
    imaging_study: ['FHIR_REFERENCE'],
    conclusion: ['TEXT_LONG'],
    conclusion_code: ['SNOMED_CT', 'ICD10', 'CODE'],
    presented_form: ['TEXT_SHORT'],
  },
  fhir_allergy_intolerance: {
    resource_id: ['ID_UUID', 'FHIR_REFERENCE'],
    resource_type: ['FHIR_RESOURCE_TYPE'],
    clinical_status: ['CODE'],
    verification_status: ['CODE'],
    type: ['CODE'],
    category: ['CODE'],
    criticality: ['CODE'],
    code_rxnorm: ['RXNORM'],
    code_snomed: ['SNOMED_CT'],
    code_ndc: ['NDC'],
    code_display: ['TEXT_SHORT'],
    patient: ['FHIR_REFERENCE'],
    encounter: ['FHIR_REFERENCE'],
    onset_datetime: ['DATE_ISO'],
    onset_age: ['ID_NUMERIC'],
    onset_string: ['TEXT_SHORT'],
    recorded_date: ['DATE_ISO'],
    recorder: ['FHIR_REFERENCE'],
    asserter: ['FHIR_REFERENCE'],
    last_occurrence: ['DATE_ISO'],
    note: ['TEXT_LONG'],
    reaction_substance: ['RXNORM', 'SNOMED_CT', 'CODE'],
    reaction_manifestation: ['SNOMED_CT', 'CODE'],
    reaction_severity: ['CODE'],
    reaction_onset: ['DATE_ISO'],
    reaction_note: ['TEXT_LONG'],
  },
  fhir_immunization: {
    resource_id: ['ID_UUID', 'FHIR_REFERENCE'],
    resource_type: ['FHIR_RESOURCE_TYPE'],
    status: ['CODE'],
    status_reason: ['CODE'],
    vaccine_code_cvx: ['CODE', 'ID_NUMERIC'],
    vaccine_code_snomed: ['SNOMED_CT'],
    vaccine_code_display: ['TEXT_SHORT'],
    patient: ['FHIR_REFERENCE'],
    encounter: ['FHIR_REFERENCE'],
    occurrence_datetime: ['DATE_ISO'],
    occurrence_string: ['TEXT_SHORT'],
    recorded: ['DATE_ISO'],
    primary_source: ['BOOLEAN'],
    report_origin: ['CODE'],
    location: ['FHIR_REFERENCE'],
    manufacturer: ['TEXT_SHORT', 'FHIR_REFERENCE'],
    lot_number: ['ID_ALPHANUMERIC'],
    expiration_date: ['DATE', 'DATE_ISO'],
    site: ['SNOMED_CT', 'CODE'],
    route: ['SNOMED_CT', 'CODE'],
    dose_quantity: ['ID_NUMERIC'],
    dose_unit: ['CODE'],
    performer: ['FHIR_REFERENCE'],
    performer_function: ['CODE'],
    note: ['TEXT_LONG'],
    reason_code: ['SNOMED_CT', 'CODE'],
    is_subpotent: ['BOOLEAN'],
    subpotent_reason: ['CODE'],
  },
  fhir_care_plan: {
    resource_id: ['ID_UUID', 'FHIR_REFERENCE'],
    resource_type: ['FHIR_RESOURCE_TYPE'],
    status: ['CODE'],
    intent: ['CODE'],
    category: ['SNOMED_CT', 'CODE'],
    title: ['TEXT_SHORT'],
    description: ['TEXT_LONG'],
    subject: ['FHIR_REFERENCE'],
    encounter: ['FHIR_REFERENCE'],
    period_start: ['DATE_ISO'],
    period_end: ['DATE_ISO'],
    created: ['DATE_ISO'],
    author: ['FHIR_REFERENCE'],
    contributor: ['FHIR_REFERENCE'],
    care_team: ['FHIR_REFERENCE'],
    addresses: ['FHIR_REFERENCE'],
    supporting_info: ['FHIR_REFERENCE'],
    goal: ['FHIR_REFERENCE'],
    activity_detail_status: ['CODE'],
    activity_detail_code: ['SNOMED_CT', 'CPT', 'CODE'],
    activity_detail_description: ['TEXT_LONG'],
    activity_detail_scheduled: ['DATE_ISO', 'TEXT_SHORT'],
    activity_detail_performer: ['FHIR_REFERENCE'],
    note: ['TEXT_LONG'],
  },
  fhir_risk_assessment: {
    resource_id: ['ID_UUID', 'FHIR_REFERENCE'],
    resource_type: ['FHIR_RESOURCE_TYPE'],
    status: ['CODE'],
    method: ['SNOMED_CT', 'CODE'],
    code: ['SNOMED_CT', 'LOINC', 'CODE'],
    subject: ['FHIR_REFERENCE'],
    encounter: ['FHIR_REFERENCE'],
    occurrence_datetime: ['DATE_ISO'],
    occurrence_period_start: ['DATE_ISO'],
    occurrence_period_end: ['DATE_ISO'],
    condition: ['FHIR_REFERENCE'],
    performer: ['FHIR_REFERENCE'],
    reason_code: ['SNOMED_CT', 'ICD10', 'CODE'],
    reason_reference: ['FHIR_REFERENCE'],
    basis: ['FHIR_REFERENCE'],
    prediction_outcome: ['CODE', 'SNOMED_CT'],
    prediction_probability: ['PERCENTAGE', 'ID_NUMERIC'],
    prediction_qualitative_risk: ['CODE'],
    prediction_when: ['DATE_ISO', 'TEXT_SHORT'],
    prediction_rationale: ['TEXT_LONG'],
    mitigation: ['TEXT_LONG'],
    note: ['TEXT_LONG'],
  },
};

/**
 * Column name synonyms for matching
 */
export const COLUMN_SYNONYMS: Record<string, string[]> = {
  // Staff/Person identifiers
  first_name: ['fname', 'firstname', 'first', 'given_name', 'givenname', 'forename'],
  last_name: ['lname', 'lastname', 'last', 'surname', 'family_name', 'familyname'],
  middle_name: ['mname', 'middlename', 'middle', 'mi', 'middle_initial'],
  email: ['email_address', 'emailaddress', 'e_mail', 'mail', 'work_email'],
  phone_work: ['work_phone', 'workphone', 'office_phone', 'business_phone', 'phone', 'telephone'],
  phone_mobile: ['mobile', 'cell', 'cellphone', 'cell_phone', 'mobile_phone', 'personal_phone'],
  phone_home: ['home_phone', 'homephone'],
  npi: ['npi_number', 'national_provider_id', 'provider_npi', 'npi_id'],
  dea_number: ['dea', 'dea_num', 'dea_id', 'dea_license'],
  employee_id: ['emp_id', 'empid', 'employee_number', 'emp_num', 'staff_id', 'badge', 'badge_id', 'personnel_id'],
  hire_date: ['start_date', 'startdate', 'date_hired', 'employment_date', 'hire_dt', 'employed_since'],
  termination_date: ['end_date', 'enddate', 'term_date', 'separation_date', 'term_dt', 'last_day'],
  date_of_birth: ['dob', 'birthdate', 'birth_date', 'birthday', 'birth_dt'],
  address_line1: ['address', 'street', 'street_address', 'addr1', 'address1', 'addr'],
  address_line2: ['address2', 'addr2', 'suite', 'apt', 'unit', 'apartment'],
  city: ['city_name', 'town'],
  state: ['state_code', 'st', 'province', 'state_abbr'],
  zip: ['zipcode', 'zip_code', 'postal', 'postal_code', 'postalcode'],
  department_name: ['dept', 'department', 'dept_name', 'division'],
  department_code: ['dept_code', 'dept_id', 'department_id', 'dept_num'],
  license_number: ['lic_num', 'license_num', 'license_no', 'lic_no', 'license_id'],
  expiration_date: ['exp_date', 'expires', 'expiry', 'expiration', 'exp_dt', 'valid_until'],
  issued_date: ['issue_date', 'issue_dt', 'granted_date', 'effective_date'],
  facility_name: ['location', 'site', 'site_name', 'building', 'campus'],
  facility_code: ['location_code', 'site_code', 'site_id', 'building_code'],
  employment_status: ['status', 'emp_status', 'active_status', 'employee_status'],
  employment_type: ['emp_type', 'job_type', 'position_type', 'work_type'],
  gender: ['sex', 'gender_code'],
  preferred_name: ['nickname', 'goes_by', 'known_as', 'alias'],

  // FHIR Clinical Synonyms
  identifier_mrn: ['mrn', 'medical_record_number', 'med_rec_num', 'patient_id', 'patient_number', 'chart_number', 'account_number'],
  identifier_ssn: ['ssn', 'social_security', 'social_security_number', 'ssn_last_4'],
  name_given: ['first_name', 'given', 'fname', 'patient_first_name', 'pt_first'],
  name_family: ['last_name', 'family', 'lname', 'patient_last_name', 'pt_last', 'surname'],
  birth_date: ['dob', 'date_of_birth', 'birthdate', 'birthday', 'patient_dob', 'pt_dob'],
  telecom_phone: ['phone', 'telephone', 'contact_phone', 'patient_phone', 'pt_phone'],
  telecom_email: ['email', 'patient_email', 'contact_email', 'pt_email'],
  address_line: ['address', 'street_address', 'patient_address', 'home_address', 'addr1'],
  address_postal_code: ['zip', 'zipcode', 'zip_code', 'postal_code', 'patient_zip'],
  address_city: ['city', 'patient_city', 'home_city'],
  address_state: ['state', 'patient_state', 'home_state', 'state_code'],
  marital_status: ['marital', 'marital_code', 'marriage_status'],

  // Observation/Vital signs
  code_loinc: ['loinc', 'loinc_code', 'loinc_num', 'observation_code', 'test_code', 'lab_code'],
  code_snomed: ['snomed', 'snomed_code', 'snomed_ct', 'clinical_code', 'diagnosis_code'],
  value_quantity: ['result', 'value', 'result_value', 'test_result', 'lab_value', 'numeric_result'],
  value_quantity_unit: ['unit', 'units', 'uom', 'result_unit', 'measurement_unit'],
  value_string: ['result_text', 'text_result', 'string_result', 'narrative_result'],
  effective_datetime: ['observation_date', 'result_date', 'test_date', 'collected_date', 'specimen_date'],
  reference_range_low: ['low_range', 'ref_low', 'normal_low', 'range_low'],
  reference_range_high: ['high_range', 'ref_high', 'normal_high', 'range_high'],
  interpretation: ['abnormal_flag', 'result_flag', 'interp', 'interpretation_code'],

  // Condition/Diagnosis
  code_icd10: ['icd10', 'icd_10', 'icd10_code', 'diagnosis_code', 'dx_code', 'icd_code'],
  clinical_status: ['status', 'condition_status', 'dx_status', 'active_inactive'],
  verification_status: ['verified', 'confirmed', 'verification', 'dx_verification'],
  onset_datetime: ['onset', 'onset_date', 'diagnosis_date', 'dx_date', 'start_date', 'diagnosed_on'],
  abatement_datetime: ['resolved', 'resolved_date', 'end_date', 'resolution_date'],
  recorded_date: ['entry_date', 'documented_date', 'record_date', 'charted_date'],
  severity: ['acuity', 'condition_severity', 'dx_severity', 'priority'],
  body_site: ['location', 'anatomical_site', 'site', 'body_part', 'laterality'],

  // Medication
  medication_rxnorm: ['rxnorm', 'rxnorm_code', 'rx_code', 'drug_code', 'ndc_rxnorm'],
  medication_ndc: ['ndc', 'ndc_code', 'national_drug_code', 'drug_ndc'],
  medication_display: ['medication', 'drug_name', 'med_name', 'prescription', 'rx_name'],
  dosage_text: ['dosage', 'dose', 'sig', 'instructions', 'dosing_instructions', 'directions'],
  dosage_route: ['route', 'admin_route', 'route_of_administration', 'delivery_route'],
  dosage_dose_quantity: ['dose_amount', 'quantity', 'dose_qty', 'amount'],
  dosage_dose_unit: ['dose_unit', 'strength_unit', 'dosage_unit'],
  dispense_quantity: ['quantity_dispensed', 'qty', 'amount_dispensed', 'fill_qty'],
  number_of_refills: ['refills', 'refill_count', 'refills_remaining', 'refill_number'],
  days_supply: ['supply_days', 'day_supply', 'days'],
  authored_on: ['prescription_date', 'rx_date', 'order_date', 'written_date'],

  // Procedure
  code_cpt: ['cpt', 'cpt_code', 'procedure_code', 'service_code', 'billing_code'],
  performed_datetime: ['procedure_date', 'service_date', 'performed_date', 'surgery_date'],
  performer: ['provider', 'performing_provider', 'surgeon', 'physician', 'practitioner'],
  outcome: ['result', 'procedure_outcome', 'surgery_outcome'],

  // Encounter/Visit
  class_code: ['encounter_type', 'visit_type', 'patient_class', 'service_type'],
  period_start: ['admit_date', 'admission_date', 'visit_date', 'start_date', 'arrival_date'],
  period_end: ['discharge_date', 'end_date', 'departure_date', 'checkout_date'],
  hospitalization_admit_source: ['admit_source', 'referral_source', 'admission_source'],
  hospitalization_discharge_disposition: ['discharge_disposition', 'discharge_status', 'discharge_type'],
  reason_code: ['chief_complaint', 'reason_for_visit', 'presenting_problem', 'visit_reason'],
  service_provider: ['facility', 'hospital', 'clinic', 'organization'],

  // Diagnostic Report
  conclusion: ['impression', 'findings', 'result_summary', 'report_conclusion', 'interpretation'],
  conclusion_code: ['finding_code', 'impression_code', 'result_code'],
  results_interpreter: ['radiologist', 'pathologist', 'interpreting_physician', 'reading_physician'],

  // Allergy
  criticality: ['severity', 'allergy_severity', 'reaction_severity', 'risk_level'],
  code_rxnorm: ['allergen_rxnorm', 'substance_code', 'drug_allergen'],
  reaction_manifestation: ['reaction', 'symptom', 'adverse_reaction', 'reaction_type'],
  last_occurrence: ['last_reaction', 'most_recent_reaction', 'last_episode'],

  // Immunization/Vaccine
  vaccine_code_cvx: ['cvx', 'cvx_code', 'vaccine_code', 'immunization_code'],
  lot_number: ['lot', 'batch_number', 'lot_num', 'vaccine_lot'],
  site: ['injection_site', 'admin_site', 'body_site'],
  route: ['admin_route', 'administration_route', 'injection_route'],

  // Care Plan
  title: ['plan_name', 'care_plan_name', 'plan_title'],
  description: ['plan_description', 'care_plan_description', 'summary'],
  goal: ['treatment_goal', 'care_goal', 'objective'],
  activity_detail_code: ['intervention', 'activity_code', 'treatment_code'],

  // Risk Assessment
  prediction_probability: ['risk_score', 'probability', 'likelihood', 'risk_percentage', 'risk_level'],
  prediction_outcome: ['predicted_outcome', 'risk_outcome', 'projected_outcome'],
  mitigation: ['intervention', 'prevention', 'risk_mitigation', 'action_plan'],

  // Common FHIR references
  subject: ['patient', 'patient_reference', 'subject_reference', 'pt_ref'],
  encounter: ['visit', 'encounter_reference', 'visit_reference', 'admission'],
  requester: ['ordering_provider', 'prescriber', 'ordered_by', 'requesting_physician'],
  recorder: ['documenter', 'entered_by', 'documented_by', 'charted_by'],
  asserter: ['reported_by', 'informant', 'source', 'information_source'],
};
