[build]
  command = "npm run build"
  publish = "build"

[secrets_scan]
  omit_keys = [
    "REACT_APP_WEATHER_API_KEY",
    "REACT_APP_SUPABASE_URL",
    "REACT_APP_SUPABASE_ANON_KEY",
    "REACT_APP_FIREBASE_VAPID_KEY"
  ]
