[build]
  command = "npm run build"
  publish = "build"

[secrets]
  omit_keys = [
    "REACT_APP_SUPABASE_URL",
    "REACT_APP_SUPABASE_ANON_KEY",
    "REACT_APP_FIREBASE_VAPID_KEY",
    "REACT_APP_WEATHER_API_KEY"
  ]
  omit_paths = [
    "build/static/js/",
    "dist/components/WeatherWidget.js"
  ]

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline';"
