/**
 * ToolSigning tests — Guardian Option B Session 2 (ES256 tool signatures).
 *
 * Uses a FIXED TEST keypair (safe to commit — test-only, never used in prod;
 * the real key is generated by Maria via guardian-generate-signing-key.mjs).
 */

import { describe, it, expect, vi, afterEach } from 'vitest';

// Fixed test key material (P-256). The signature below is ES256 over the
// deterministic builtin checksum of guardian.retry-api@1.0.0.
const RETRY_API_CHECKSUM = '0000000063660e440000000021174912000000004271475200000000847d5756';
const RETRY_API_SIGNATURE =
  'E1pAAqlhDV4HHeeUSKyMOLKXM1SzAP7iqAM_5cF19yzW4yOTf64swwadVZPnsrCfHC6YBm0yU1Hav97P7-RB8w';
const TEST_KEY_ID = 'guardian-es256-test';

vi.mock('../guardianSigningKey', () => ({
  GUARDIAN_SIGNING_PUBLIC_KEY: {
    keyId: 'guardian-es256-test',
    jwk: {
      key_ops: ['verify'], ext: true, kty: 'EC',
      x: 'cxO5nCrkZ5YO7kHKjSL2SSJxEpGj1Huhp7ww-DpHrQg',
      y: '7Jy1fRCtxITzVRctzEKZo3iGXlbwfEsdTsTBfOJxwUs',
      crv: 'P-256',
    },
  },
}));

vi.mock('../../auditLogger', () => ({
  auditLogger: {
    info: vi.fn().mockResolvedValue(undefined),
    warn: vi.fn().mockResolvedValue(undefined),
    error: vi.fn().mockResolvedValue(undefined),
  },
}));

import { verifyToolSignature, getSigningMode } from '../ToolSigning';

describe('ToolSigning (key provisioned via test mock)', () => {
  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it('defaults to warn mode when the flag is not set to enforce', () => {
    expect(getSigningMode()).toBe('warn');
  });

  it('enforce mode requires VITE_GUARDIAN_REQUIRE_SIGNATURES=enforce', () => {
    vi.stubEnv('VITE_GUARDIAN_REQUIRE_SIGNATURES', 'enforce');
    expect(getSigningMode()).toBe('enforce');
  });

  it('accepts a valid ES256 signature over the tool checksum', async () => {
    const verdict = await verifyToolSignature('guardian.retry-api', RETRY_API_CHECKSUM, {
      signature: RETRY_API_SIGNATURE,
      keyId: TEST_KEY_ID,
      signedAt: '2026-07-23T00:00:00Z',
    });
    expect(verdict.valid).toBe(true);
  });

  it('rejects when the checksum was tampered (single byte)', async () => {
    const tampered = RETRY_API_CHECKSUM.slice(0, -1) + '7';
    const verdict = await verifyToolSignature('guardian.retry-api', tampered, {
      signature: RETRY_API_SIGNATURE,
      keyId: TEST_KEY_ID,
      signedAt: '2026-07-23T00:00:00Z',
    });
    expect(verdict.valid).toBe(false);
    expect(verdict.reason).toContain('signature does not match');
  });

  it('rejects a signature from a different key id', async () => {
    const verdict = await verifyToolSignature('guardian.retry-api', RETRY_API_CHECKSUM, {
      signature: RETRY_API_SIGNATURE,
      keyId: 'some-other-key',
      signedAt: '2026-07-23T00:00:00Z',
    });
    expect(verdict.valid).toBe(false);
    expect(verdict.reason).toContain('does not match the provisioned key');
  });

  it('reports unsigned tools (no record anywhere)', async () => {
    const verdict = await verifyToolSignature('guardian.unsigned-tool', RETRY_API_CHECKSUM);
    expect(verdict.valid).toBe(false);
    expect(verdict.reason).toContain('no signature on file');
  });
});
