/**
 * Immunization Registry — Constants
 *
 * Registry config + HL7 code maps (CVX, MVX, administration site/route).
 * Extracted from immunizationRegistryService.ts (god-file decomposition).
 */

import type { RegistryConfig } from './types';

// Texas ImmTrac2 configuration
export const TX_IMMTRAC2_CONFIG: RegistryConfig = {
  name: 'TX_IMMTRAC2',
  endpoint: 'https://immtrac.dshs.texas.gov/hl7', // Production endpoint
  sendingApplication: 'WELLFIT_EHR',
  receivingApplication: 'IMMTRAC2',
  receivingFacility: 'TX_DSHS',
  hl7Version: '2.5.1',
};

// CVX Code to vaccine name mapping (common vaccines)
export const CVX_VACCINE_NAMES: Record<string, string> = {
  '03': 'MMR',
  '08': 'Hepatitis B, adolescent or pediatric',
  '09': 'Td (adult)',
  '10': 'IPV',
  '20': 'DTaP',
  '21': 'Varicella',
  '33': 'Pneumococcal polysaccharide PPV23',
  '43': 'Hepatitis B, adult',
  '44': 'Hepatitis B, dialysis',
  '45': 'Hepatitis B, unspecified',
  '48': 'Hib (PRP-T)',
  '49': 'Hib (PRP-OMP)',
  '52': 'Hepatitis A, adult',
  '83': 'Hepatitis A, pediatric',
  '88': 'Influenza, unspecified',
  '94': 'MMRV',
  '104': 'Hepatitis A and Hepatitis B',
  '110': 'DTaP-Hep B-IPV',
  '113': 'Td (adult)',
  '114': 'Meningococcal MCV4P',
  '115': 'Tdap',
  '116': 'Rotavirus, pentavalent',
  '118': 'HPV, bivalent',
  '119': 'Rotavirus, monovalent',
  '120': 'DTaP-Hib-IPV',
  '121': 'Zoster, live',
  '133': 'PCV13',
  '136': 'Meningococcal MCV4O',
  '140': 'Influenza, seasonal, injectable',
  '141': 'Influenza, seasonal, intranasal',
  '149': 'Influenza, live, intranasal, quadrivalent',
  '150': 'Influenza, injectable, quadrivalent',
  '158': 'Influenza, injectable, quadrivalent',
  '161': 'Influenza, injectable, quadrivalent (trivalent)',
  '162': 'Meningococcal B, recombinant',
  '163': 'Meningococcal B, OMV',
  '165': 'HPV9',
  '185': 'Influenza, quadrivalent, recombinant',
  '187': 'Zoster, recombinant',
  '189': 'Hepatitis B, recombinant',
  '197': 'Influenza, high dose, quadrivalent',
  '207': 'COVID-19, mRNA, LNP-S, PF, 100 mcg/0.5 mL',
  '208': 'COVID-19, mRNA, LNP-S, PF, 30 mcg/0.3 mL',
  '210': 'COVID-19, viral vector',
  '211': 'COVID-19, mRNA',
  '212': 'COVID-19, viral vector',
  '213': 'COVID-19, mRNA',
  '217': 'COVID-19, mRNA, LNP-S, PF, pediatric',
  '218': 'COVID-19, mRNA, LNP-S, PF, 50 mcg/0.25 mL',
  '219': 'COVID-19, mRNA, LNP-S, PF, 3 mcg',
  '221': 'COVID-19, mRNA, LNP-S, bivalent',
  '228': 'COVID-19, mRNA, LNP-S, bivalent',
  '229': 'COVID-19, mRNA, LNP-S, bivalent',
  '230': 'COVID-19, mRNA, LNP-S, bivalent',
  '300': 'COVID-19, mRNA, LNP-S, 2023-2024',
  '301': 'COVID-19, mRNA, LNP-S, 2023-2024',
  '302': 'COVID-19, mRNA, LNP-S, 2023-2024',
};

// MVX (Manufacturer) codes
export const MVX_MANUFACTURERS: Record<string, string> = {
  'AB': 'Abbott',
  'ALP': 'Alpha Therapeutic Corp',
  'AVI': 'Aviron',
  'BA': 'Baxter Healthcare',
  'BAY': 'Bayer Corp',
  'BPC': 'Berna Products Corp',
  'BN': 'Bharat Biotech',
  'CNJ': 'Cangene Corp',
  'CON': 'Connaught',
  'CMP': 'Celltech Medeva Pharmaceuticals',
  'EVN': 'Evans Medical Ltd',
  'GEO': 'GeoVax Labs',
  'GRE': 'Greer Labs',
  'GSK': 'GlaxoSmithKline',
  'IDB': 'ID Biomedical',
  'IUS': 'Immuno-US',
  'JNJ': 'Johnson & Johnson',
  'JPN': 'Japanese Manufacturer',
  'KGC': 'Korea Green Cross',
  'LED': 'Lederle',
  'MBL': 'Massachusetts Biological Labs',
  'MED': 'MedImmune',
  'MSD': 'Merck & Co',
  'NAB': 'NABI',
  'NOV': 'Novartis',
  'NVX': 'Novavax',
  'OTC': 'Organon Teknika Corp',
  'ORT': 'Ortho Clinical Diagnostics',
  'PD': 'Parke-Davis',
  'PFR': 'Pfizer',
  'PMC': 'sanofi pasteur',
  'PRX': 'Protein Sciences',
  'SCL': 'Sclavo',
  'SKB': 'SmithKline Beecham',
  'SOL': 'Solvay Pharmaceuticals',
  'TAL': 'Talecris Biotherapeutics',
  'USA': 'US Army Medical R&D Command',
  'VXG': 'VaxGen',
  'WAL': 'Wyeth-Ayerst',
  'WY': 'Wyeth',
  'MOD': 'Moderna',
  'JSN': 'Janssen',
  'ASZ': 'AstraZeneca',
  'BNT': 'BioNTech',
  'PFE': 'Pfizer',
};

// Administration site codes (HL7 Table 0163)
export const ADMIN_SITE_CODES: Record<string, string> = {
  'LA': 'Left Arm',
  'RA': 'Right Arm',
  'LT': 'Left Thigh',
  'RT': 'Right Thigh',
  'LLFA': 'Left Lower Forearm',
  'RLFA': 'Right Lower Forearm',
  'LD': 'Left Deltoid',
  'RD': 'Right Deltoid',
  'LG': 'Left Gluteus Medius',
  'RG': 'Right Gluteus Medius',
  'LVL': 'Left Vastus Lateralis',
  'RVL': 'Right Vastus Lateralis',
};

// Administration route codes (NCI/HL7)
export const ADMIN_ROUTE_CODES: Record<string, string> = {
  'IM': 'Intramuscular',
  'SC': 'Subcutaneous',
  'ID': 'Intradermal',
  'PO': 'Oral',
  'IN': 'Intranasal',
  'IV': 'Intravenous',
  'TD': 'Transdermal',
};
