/**
 * Revenue & Billing Section Definitions
 * Extracted from sectionDefinitions.tsx for 600-line compliance.
 *
 * Copyright (c) 2025-2026 Envision Virtual Edge Group LLC. All rights reserved.
 */

import React, { Suspense } from 'react';
import { DashboardSection } from './types';
import { SectionLoadingFallback } from './sectionDefinitions';
import { SDOHCoderAssistWrapper } from './SDOHCoderAssistWrapper';
import {
  SmartScribe,
  RevenueDashboard,
  CCMTimeline,
  ClaimsSubmissionPanel,
  ClaimsAppealsPanel,
  PriorAuthDashboard,
  BillingDashboard,
  BillingProviderForm,
  StaffFinancialSavingsTracker,
  SuperbillReviewPanel,
  ClaimAgingDashboard,
  UndercodingDetectionDashboard,
  DocumentationGapDashboard,
  HCCOpportunityDashboard,
  BillingQueueDashboard,
  EligibilityVerificationPanel,
  ERAPaymentPostingDashboard,
  ClaimResubmissionDashboard,
} from './lazyImports';

export const getRevenueSections = (): DashboardSection[] => [
  {
    id: 'smartscribe-atlus',
    title: 'SmartScribe Atlus',
    subtitle: 'AI transcription for maximum billing accuracy',
    icon: '\uD83C\uDFA4',
    headerColor: 'text-purple-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><SmartScribe /></Suspense>,
    category: 'revenue',
    priority: 'high',
  },
  {
    id: 'revenue-dashboard',
    title: 'Revenue Dashboard',
    subtitle: 'Real-time revenue analytics and optimization opportunities',
    icon: '\uD83D\uDCB0',
    headerColor: 'text-green-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><RevenueDashboard /></Suspense>,
    category: 'revenue',
    priority: 'high',
  },
  {
    id: 'ccm-autopilot',
    title: 'CCM Autopilot',
    subtitle: 'Automatic tracking of 20+ minute patient interactions for CCM billing',
    icon: '\u23F1\uFE0F',
    headerColor: 'text-purple-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><CCMTimeline /></Suspense>,
    category: 'revenue',
    priority: 'medium',
  },
  {
    id: 'claims-submission',
    title: 'Claims Submission Center',
    subtitle: 'Generate and submit 837P claims to clearinghouses',
    icon: '\uD83D\uDCCB',
    headerColor: 'text-blue-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ClaimsSubmissionPanel /></Suspense>,
    category: 'revenue',
    priority: 'medium',
  },
  {
    id: 'claims-appeals',
    title: 'Claims Appeals & Resubmission',
    subtitle: 'AI-assisted appeal letters for denied claims',
    icon: '\uD83D\uDD04',
    headerColor: 'text-red-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ClaimsAppealsPanel /></Suspense>,
    category: 'revenue',
    priority: 'medium',
  },
  {
    id: 'prior-auth',
    title: 'Prior Authorization Center',
    subtitle: 'CMS-0057-F compliant prior auth requests, decisions, and appeals',
    icon: '\uD83D\uDEE1\uFE0F',
    headerColor: 'text-indigo-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><PriorAuthDashboard /></Suspense>,
    category: 'revenue',
    priority: 'high',
    roles: ['admin', 'super_admin', 'case_manager', 'billing_specialist'],
  },
  {
    id: 'sdoh-billing',
    title: 'SDOH Billing Encoder',
    subtitle: 'Social determinants of health-aware medical coding',
    icon: '\uD83C\uDFE5',
    headerColor: 'text-indigo-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><SDOHCoderAssistWrapper /></Suspense>,
    category: 'revenue',
    priority: 'low',
  },
  {
    id: 'provider-registry',
    title: 'Provider Registry',
    subtitle: 'Register and verify billing providers via NPI Registry — auto-populate from NPPES',
    icon: '\uD83C\uDFE5',
    headerColor: 'text-purple-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><BillingProviderForm /></Suspense>,
    category: 'revenue',
    priority: 'high',
    roles: ['admin', 'super_admin', 'billing_specialist'],
  },
  {
    id: 'billing-dashboard',
    title: 'Billing & Claims Management',
    subtitle: 'Monitor claims processing and revenue tracking',
    icon: '\uD83D\uDCB3',
    headerColor: 'text-green-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><BillingDashboard /></Suspense>,
    category: 'revenue',
    priority: 'medium',
  },
  {
    id: 'staff-financial-savings',
    title: 'Staff Financial Savings Tracker',
    subtitle: 'Track cost savings by nurse, position, and department for budgetary analysis',
    icon: '\uD83D\uDCB5',
    headerColor: 'text-emerald-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><StaffFinancialSavingsTracker /></Suspense>,
    category: 'revenue',
    priority: 'high',
    roles: ['admin', 'super_admin', 'finance', 'billing_specialist'],
  },
  {
    id: 'superbill-review',
    title: 'Superbill Provider Sign-Off',
    subtitle: 'Review and approve superbills before clearinghouse submission',
    icon: '\u2705',
    headerColor: 'text-green-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><SuperbillReviewPanel /></Suspense>,
    category: 'revenue',
    priority: 'high',
    roles: ['admin', 'super_admin', 'physician', 'billing_specialist'],
  },
  {
    id: 'claim-aging',
    title: 'Claim Aging Dashboard',
    subtitle: 'Track claims by aging bucket to identify revenue bottlenecks and stalled submissions',
    icon: '\u23F3',
    headerColor: 'text-amber-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ClaimAgingDashboard /></Suspense>,
    category: 'revenue',
    priority: 'high',
    roles: ['admin', 'super_admin', 'billing_specialist', 'finance'],
  },
  {
    id: 'undercoding-detection',
    title: 'Undercoding Detection',
    subtitle: 'Compare AI-suggested codes vs billed codes to identify revenue gaps and missed charges',
    icon: '\uD83D\uDD0E',
    headerColor: 'text-orange-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><UndercodingDetectionDashboard /></Suspense>,
    category: 'revenue',
    priority: 'high',
    roles: ['admin', 'super_admin', 'billing_specialist', 'physician', 'finance'],
  },
  {
    id: 'documentation-gap',
    title: 'Documentation Gap Indicator',
    subtitle: 'Proactive alerts showing what to document to qualify for higher E/M levels before billing',
    icon: '\uD83D\uDCDD',
    headerColor: 'text-teal-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><DocumentationGapDashboard /></Suspense>,
    category: 'revenue',
    priority: 'high',
    roles: ['admin', 'super_admin', 'billing_specialist', 'physician'],
  },
  {
    id: 'hcc-opportunity-flags',
    title: 'HCC Opportunity Flags',
    subtitle: 'Identify expiring and missing HCC diagnoses for Medicare Advantage risk adjustment',
    icon: '\uD83C\uDFAF',
    headerColor: 'text-purple-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><HCCOpportunityDashboard /></Suspense>,
    category: 'revenue',
    priority: 'high',
    roles: ['admin', 'super_admin', 'billing_specialist', 'physician', 'finance'],
  },
  {
    id: 'billing-queue',
    title: 'Billing Queue',
    subtitle: 'Bridge signed encounters to superbill drafts — one-click superbill generation',
    icon: '\uD83D\uDCCB',
    headerColor: 'text-blue-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><BillingQueueDashboard /></Suspense>,
    category: 'revenue',
    priority: 'high',
    roles: ['admin', 'super_admin', 'billing_specialist', 'physician'],
  },
  {
    id: 'eligibility-verification',
    title: 'Eligibility Verification',
    subtitle: 'Verify patient insurance coverage (270/271) before billing to prevent denials',
    icon: '\uD83D\uDEE1\uFE0F',
    headerColor: 'text-indigo-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><EligibilityVerificationPanel /></Suspense>,
    category: 'revenue',
    priority: 'high',
    roles: ['admin', 'super_admin', 'billing_specialist'],
  },
  {
    id: 'era-payment-posting',
    title: 'ERA Payment Posting',
    subtitle: 'Match ERA/835 remittance advice to claims and post payments to close the revenue cycle',
    icon: '\uD83D\uDCB3',
    headerColor: 'text-green-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ERAPaymentPostingDashboard /></Suspense>,
    category: 'revenue',
    priority: 'high',
    roles: ['admin', 'super_admin', 'billing_specialist', 'finance'],
  },
  {
    id: 'claim-resubmission',
    title: 'Claim Resubmission Workflow',
    subtitle: 'Correct denied claims, track resubmission chains, and void unrecoverable claims',
    icon: '\uD83D\uDD04',
    headerColor: 'text-red-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ClaimResubmissionDashboard /></Suspense>,
    category: 'revenue',
    priority: 'high',
    roles: ['admin', 'super_admin', 'billing_specialist', 'finance'],
  },
];
