/**
 * Admin Panel Section Definitions
 * Extracted from IntelligentAdminPanel for code splitting
 *
 * Lazy imports extracted to lazyImports.tsx for 600-line compliance.
 * Revenue sections extracted to revenueSections.tsx for 600-line compliance.
 */

import React, { Suspense } from 'react';
import { DashboardSection } from './types';
import {
  UsersList,
  ReportsSection,
  ExportCheckIns,
  FhirAiDashboard,
  FHIRFormBuilderEnhanced,
  FHIRDataMapper,
  HL7MessageTestPanel,
  AdminTransferLogs,
  PatientEngagementDashboard,
  HospitalPatientEnrollment,
  PaperFormScanner,
  ShiftHandoffDashboard,
  TenantSecurityDashboard,
  TenantAuditLogs,
  TenantComplianceReport,
  TenantConfigHistory,
  TenantModuleConfigPanel,
  FacilityManagementPanel,
  ClearinghouseConfigPanel,
  MfaComplianceDashboard,
  QualityMeasuresDashboard,
  CardiologyDashboard,
  LaborDeliveryDashboard,
  OncologyDashboard,
  CareGapDashboard,
  ClinicalNoteSummaryDashboard,
  AIModelCardsDashboard,
  ProviderAssignmentDashboard,
  UnacknowledgedResultsDashboard,
  ProviderTaskQueueDashboard,
  PublicHealthReportingDashboard,
  BreachNotificationDashboard,
  BAATrackingDashboard,
  PatientAmendmentReviewQueue,
  TrainingComplianceDashboard,
  ReferralAgingDashboard,
  ReferralCompletionDashboard,
  EncounterAuditTimeline,
  ResultEscalationDashboard,
  ProviderCoverageDashboard,
  UserRoleManagementPanel,
  UserProvisioningPanel,
} from './lazyImports';
import { getRevenueSections } from './revenueSections';

// Loading fallback for lazy-loaded sections
export const SectionLoadingFallback: React.FC = () => (
  <div className="flex items-center justify-center p-8">
    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
    <span className="ml-3 text-gray-600">Loading section...</span>
  </div>
);

/**
 * All available admin panel sections
 * Organized by category for easy maintenance
 */
export const getAllSections = (): DashboardSection[] => [
  // ==================== REVENUE & BILLING ====================
  ...getRevenueSections(),

  // ==================== PATIENT CARE ====================
  {
    id: 'patient-engagement',
    title: 'Patient Engagement & Risk Assessment',
    subtitle: 'Monitor senior activity levels to identify at-risk patients',
    icon: '\uD83D\uDCCA',
    headerColor: 'text-indigo-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><PatientEngagementDashboard /></Suspense>,
    category: 'patient-care',
    priority: 'high',
  },
  {
    id: 'provider-assignment',
    title: 'Encounter Provider Assignments',
    subtitle: 'Assign attending, supervising, and consulting providers to clinical encounters',
    icon: '\uD83D\uDC68\u200D\u2695\uFE0F',
    headerColor: 'text-blue-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ProviderAssignmentDashboard /></Suspense>,
    category: 'patient-care',
    priority: 'high',
    roles: ['admin', 'super_admin', 'physician', 'nurse'],
  },
  {
    id: 'unacknowledged-results',
    title: 'Unacknowledged Results',
    subtitle: 'Track and acknowledge critical lab and imaging results requiring clinician review',
    icon: '\uD83D\uDD2C',
    headerColor: 'text-red-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><UnacknowledgedResultsDashboard /></Suspense>,
    category: 'patient-care',
    priority: 'high',
    roles: ['admin', 'super_admin', 'physician', 'nurse', 'lab_tech'],
  },
  {
    id: 'provider-task-queue',
    title: 'Provider Task Queue',
    subtitle: 'Inbox routing with SLA deadlines, escalation tracking, and task lifecycle management',
    icon: '\uD83D\uDCCB',
    headerColor: 'text-orange-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ProviderTaskQueueDashboard /></Suspense>,
    category: 'patient-care',
    priority: 'high',
    roles: ['admin', 'super_admin', 'physician', 'nurse', 'case_manager'],
  },
  {
    id: 'result-escalation',
    title: 'Result Escalation Rules Engine',
    subtitle: 'Auto-route abnormal lab values to specialist providers with SLA tracking and audit trail',
    icon: '\u2695\uFE0F',
    headerColor: 'text-red-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ResultEscalationDashboard /></Suspense>,
    category: 'patient-care',
    priority: 'high',
    roles: ['admin', 'super_admin', 'physician', 'nurse', 'lab_tech'],
  },
  {
    id: 'provider-coverage',
    title: 'Provider Coverage & On-Call',
    subtitle: 'Manage provider absence coverage, on-call rotations, and automatic task routing',
    icon: '\uD83D\uDD04',
    headerColor: 'text-teal-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ProviderCoverageDashboard /></Suspense>,
    category: 'patient-care',
    priority: 'high',
    roles: ['admin', 'super_admin', 'physician', 'nurse'],
  },
  {
    id: 'patient-handoff',
    title: 'Patient Handoff System',
    subtitle: 'Secure transfer of care between facilities - HIPAA compliant',
    icon: '\uD83C\uDFE5',
    headerColor: 'text-teal-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><AdminTransferLogs showExportButton={true} /></Suspense>,
    category: 'patient-care',
    priority: 'medium',
  },
  {
    id: 'shift-handoff',
    title: 'Smart Shift Handoff',
    subtitle: 'AI-assisted nurse shift handoff with auto-scored patient risks and real-time collaboration',
    icon: '\uD83D\uDD04',
    headerColor: 'text-blue-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ShiftHandoffDashboard /></Suspense>,
    category: 'patient-care',
    priority: 'high',
    roles: ['admin', 'super_admin', 'nurse', 'charge_nurse'],
  },
  {
    id: 'user-management',
    title: 'User Management',
    subtitle: 'Manage patient and staff accounts',
    icon: '\uD83D\uDC65',
    headerColor: 'text-gray-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><UsersList /></Suspense>,
    category: 'patient-care',
    priority: 'medium',
  },
  {
    id: 'user-role-management',
    title: 'Staff Role Management',
    subtitle: 'Assign, change, and revoke staff roles with hierarchy enforcement and audit logging',
    icon: '\uD83D\uDEE1\uFE0F',
    headerColor: 'text-blue-900',
    component: <Suspense fallback={<SectionLoadingFallback />}><UserRoleManagementPanel /></Suspense>,
    category: 'admin',
    priority: 'high',
    roles: ['admin', 'super_admin', 'department_head', 'it_admin'],
  },
  {
    id: 'user-provisioning',
    title: 'User Provisioning',
    subtitle: 'Create new user accounts and manage pending registrations',
    icon: '\uD83D\uDC64',
    headerColor: 'text-green-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><UserProvisioningPanel /></Suspense>,
    category: 'admin',
    priority: 'high',
    roles: ['admin', 'super_admin'],
  },
  {
    id: 'hospital-enrollment',
    title: 'Hospital Patient Enrollment',
    subtitle: 'Create test patients for backend testing (Physician/Nurse panels, handoffs, clinical workflows)',
    icon: '\uD83C\uDFE5',
    headerColor: 'text-blue-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><HospitalPatientEnrollment /></Suspense>,
    category: 'admin',
    priority: 'high',
    defaultOpen: false,
  },
  {
    id: 'paper-form-scanner',
    title: 'Paper Form Scanner (AI-Powered OCR)',
    subtitle: 'Upload photos of paper forms - AI extracts data automatically. Perfect for rural hospitals during outages.',
    icon: '\uD83D\uDCF8',
    headerColor: 'text-green-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><PaperFormScanner /></Suspense>,
    category: 'admin',
    priority: 'high',
    defaultOpen: false,
  },

  // ==================== CLINICAL SPECIALTIES ====================
  {
    id: 'cardiology',
    title: 'Cardiology Dashboard',
    subtitle: 'ECG, echocardiography, heart failure management, cardiac rehab, and device monitoring',
    icon: '\uD83E\uDEC0',
    headerColor: 'text-red-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><CardiologyDashboard /></Suspense>,
    category: 'clinical',
    priority: 'high',
    roles: ['admin', 'super_admin', 'physician', 'case_manager'],
  },
  {
    id: 'labor-delivery',
    title: 'Labor & Delivery Dashboard',
    subtitle: 'Prenatal care, labor tracking, fetal monitoring, delivery records, and postpartum assessments',
    icon: '\uD83D\uDC76',
    headerColor: 'text-pink-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><LaborDeliveryDashboard /></Suspense>,
    category: 'clinical',
    priority: 'high',
    roles: ['admin', 'super_admin', 'physician', 'case_manager'],
  },
  {
    id: 'oncology',
    title: 'Oncology Dashboard',
    subtitle: 'Cancer registry, TNM staging, chemotherapy/radiation tracking, CTCAE side effects, and survivorship',
    icon: '\uD83C\uDF97\uFE0F',
    headerColor: 'text-purple-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><OncologyDashboard /></Suspense>,
    category: 'clinical',
    priority: 'high',
    roles: ['admin', 'super_admin', 'physician', 'case_manager'],
  },
  {
    id: 'care-gap-detection',
    title: 'Care Gap Detection',
    subtitle: 'Identify and close preventive care gaps across your patient panel',
    icon: '\uD83D\uDD0D',
    headerColor: 'text-orange-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><CareGapDashboard /></Suspense>,
    category: 'patient-care',
    priority: 'high',
    roles: ['admin', 'super_admin', 'physician', 'nurse', 'case_manager'],
  },
  {
    id: 'clinical-note-summary',
    title: 'Clinical Note Summarization',
    subtitle: 'Review and approve AI-generated SOAP notes, progress notes, and discharge summaries',
    icon: '\uD83D\uDCDD',
    headerColor: 'text-cyan-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ClinicalNoteSummaryDashboard /></Suspense>,
    category: 'clinical',
    priority: 'high',
    roles: ['admin', 'super_admin', 'physician', 'nurse'],
  },

  // ==================== CLINICAL DATA ====================
  {
    id: 'quality-measures',
    title: 'Quality Measures Dashboard',
    subtitle: 'eCQM, HEDIS, MIPS, and Star Ratings performance tracking',
    icon: '\uD83D\uDCCA',
    headerColor: 'text-cyan-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><QualityMeasuresDashboard tenantId="" /></Suspense>,
    category: 'clinical',
    priority: 'high',
    roles: ['admin', 'super_admin', 'case_manager', 'physician'],
  },
  {
    id: 'public-health-reporting',
    title: 'Public Health Reporting',
    subtitle: 'Monitor syndromic surveillance, immunization registry, and eCR transmissions',
    icon: '\uD83D\uDCE1',
    headerColor: 'text-teal-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><PublicHealthReportingDashboard /></Suspense>,
    category: 'clinical',
    priority: 'high',
    roles: ['admin', 'super_admin', 'compliance_officer', 'physician'],
  },
  {
    id: 'fhir-analytics',
    title: 'AI-Enhanced FHIR Analytics',
    subtitle: 'Real-time patient insights and clinical decision support',
    icon: '\uD83E\uDDE0',
    headerColor: 'text-purple-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><FhirAiDashboard supabaseUrl={import.meta.env.VITE_SUPABASE_URL || ''} supabaseKey={import.meta.env.VITE_SUPABASE_ANON_KEY || ''} /></Suspense>,
    category: 'clinical',
    priority: 'medium',
  },
  {
    id: 'fhir-questionnaire',
    title: 'FHIR Questionnaire Builder',
    subtitle: 'Create standardized clinical questionnaires using AI',
    icon: '\uD83D\uDCDD',
    headerColor: 'text-blue-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><FHIRFormBuilderEnhanced /></Suspense>,
    category: 'clinical',
    priority: 'low',
  },
  {
    id: 'fhir-mapper',
    title: 'FHIR Data Mapper',
    subtitle: 'Transform legacy data into FHIR-compliant formats',
    icon: '\uD83D\uDD04',
    headerColor: 'text-teal-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><FHIRDataMapper /></Suspense>,
    category: 'clinical',
    priority: 'low',
  },
  {
    id: 'hl7-message-lab',
    title: 'HL7 / X12 Message Lab',
    subtitle: 'Parse, validate, and convert HL7 v2.x and X12 837P messages',
    icon: '\uD83D\uDD17',
    headerColor: 'text-cyan-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><HL7MessageTestPanel /></Suspense>,
    category: 'clinical',
    priority: 'low',
  },
  {
    id: 'reports-analytics',
    title: 'Reports & Analytics',
    subtitle: 'System-wide analytics and insights',
    icon: '\uD83D\uDCCA',
    headerColor: 'text-gray-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ReportsSection /></Suspense>,
    category: 'clinical',
    priority: 'low',
  },

  // ==================== REFERRAL FOLLOW-UP (Phase 1 P5) ====================
  {
    id: 'referral-aging',
    title: 'Referral Aging Analysis',
    subtitle: 'Track pending referrals by aging bucket with automated follow-up reminders and escalation',
    icon: '\uD83D\uDCC5',
    headerColor: 'text-amber-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ReferralAgingDashboard /></Suspense>,
    category: 'clinical',
    priority: 'high',
    roles: ['admin', 'super_admin', 'case_manager', 'nurse'],
  },
  {
    id: 'referral-completion',
    title: 'Specialist Confirmation Tracking',
    subtitle: 'Record specialist completion, flag overdue referrals, and close the referral loop',
    icon: '\u2705',
    headerColor: 'text-teal-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ReferralCompletionDashboard /></Suspense>,
    category: 'clinical',
    priority: 'high',
    roles: ['admin', 'super_admin', 'case_manager', 'nurse'],
  },

  // ==================== DSI TRANSPARENCY ====================
  {
    id: 'ai-model-cards',
    title: 'DSI Transparency — AI Model Cards',
    subtitle: 'HTI-1 compliant AI/ML model documentation, risk classification, and transparency',
    icon: '\uD83E\uDD16',
    headerColor: 'text-indigo-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><AIModelCardsDashboard /></Suspense>,
    category: 'security',
    priority: 'high',
    roles: ['admin', 'super_admin'],
  },

  // ==================== SECURITY & COMPLIANCE ====================
  {
    id: 'mfa-compliance',
    title: 'MFA Compliance Dashboard',
    subtitle: 'Monitor multi-factor authentication enrollment across admin and clinical staff',
    icon: '\uD83D\uDD10',
    headerColor: 'text-blue-900',
    component: <Suspense fallback={<SectionLoadingFallback />}><MfaComplianceDashboard /></Suspense>,
    category: 'security',
    priority: 'high',
    roles: ['admin', 'super_admin', 'it_admin'],
  },
  {
    id: 'tenant-security',
    title: 'Facility Security Dashboard',
    subtitle: 'Real-time security monitoring for your facility',
    icon: '\uD83D\uDEE1\uFE0F',
    headerColor: 'text-red-900',
    component: <Suspense fallback={<SectionLoadingFallback />}><TenantSecurityDashboard /></Suspense>,
    category: 'security',
    priority: 'medium',
    roles: ['admin', 'super_admin', 'it_admin'],
  },
  {
    id: 'tenant-audit-logs',
    title: 'Audit Logs',
    subtitle: 'PHI access logs and administrative actions for your facility',
    icon: '\uD83D\uDCCB',
    headerColor: 'text-indigo-900',
    component: <Suspense fallback={<SectionLoadingFallback />}><TenantAuditLogs /></Suspense>,
    category: 'security',
    priority: 'medium',
    roles: ['admin', 'super_admin', 'it_admin'],
  },
  {
    id: 'tenant-compliance',
    title: 'Compliance Report',
    subtitle: 'HIPAA and security compliance status for your facility',
    icon: '\u2705',
    headerColor: 'text-green-900',
    component: <Suspense fallback={<SectionLoadingFallback />}><TenantComplianceReport /></Suspense>,
    category: 'security',
    priority: 'low',
    roles: ['admin', 'super_admin', 'it_admin'],
  },
  {
    id: 'tenant-config-history',
    title: 'Configuration Change History',
    subtitle: 'Audit trail of all configuration changes with filters, search, and CSV/JSON export',
    icon: '\uD83D\uDD53',
    headerColor: 'text-purple-900',
    component: <Suspense fallback={<SectionLoadingFallback />}><TenantConfigHistory /></Suspense>,
    category: 'security',
    priority: 'medium',
    roles: ['admin', 'super_admin', 'it_admin'],
  },
  {
    id: 'breach-notification',
    title: 'Breach Notification Engine',
    subtitle: 'HIPAA breach incident tracking, risk assessment, and 60-day notification compliance',
    icon: '\uD83D\uDEA8',
    headerColor: 'text-red-900',
    component: <Suspense fallback={<SectionLoadingFallback />}><BreachNotificationDashboard /></Suspense>,
    category: 'security',
    priority: 'high',
    roles: ['admin', 'super_admin', 'compliance_officer'],
  },
  {
    id: 'baa-tracking',
    title: 'BAA Tracking Dashboard',
    subtitle: 'Business associate agreement lifecycle management and renewal tracking',
    icon: '\uD83D\uDCC4',
    headerColor: 'text-blue-900',
    component: <Suspense fallback={<SectionLoadingFallback />}><BAATrackingDashboard /></Suspense>,
    category: 'security',
    priority: 'medium',
    roles: ['admin', 'super_admin', 'compliance_officer'],
  },
  {
    id: 'patient-amendment-review',
    title: 'Patient Amendment Review Queue',
    subtitle: 'Review and respond to patient requests to amend their health records (45 CFR 164.526)',
    icon: '\u270F\uFE0F',
    headerColor: 'text-orange-900',
    component: <Suspense fallback={<SectionLoadingFallback />}><PatientAmendmentReviewQueue /></Suspense>,
    category: 'security',
    priority: 'medium',
    roles: ['admin', 'super_admin', 'physician', 'nurse', 'compliance_officer'],
  },
  {
    id: 'training-compliance',
    title: 'Workforce Training Compliance',
    subtitle: 'HIPAA workforce security awareness training tracking and compliance rates',
    icon: '\uD83C\uDF93',
    headerColor: 'text-violet-900',
    component: <Suspense fallback={<SectionLoadingFallback />}><TrainingComplianceDashboard /></Suspense>,
    category: 'security',
    priority: 'medium',
    roles: ['admin', 'super_admin', 'compliance_officer'],
  },

  // ==================== ENCOUNTER AUDIT (Phase 1 P6) ====================
  {
    id: 'encounter-audit-timeline',
    title: 'Encounter Audit Timeline',
    subtitle: 'Chronological audit trail of encounter status changes, field edits, amendments, and access events',
    icon: '\uD83D\uDD50',
    headerColor: 'text-indigo-900',
    component: <Suspense fallback={<SectionLoadingFallback />}><EncounterAuditTimeline /></Suspense>,
    category: 'security',
    priority: 'high',
    roles: ['admin', 'super_admin'],
  },

  // ==================== SYSTEM ADMINISTRATION ====================
  {
    id: 'facility-management',
    title: 'Facility Management',
    subtitle: 'Manage hospitals, clinics, and other facilities in your organization',
    icon: '\uD83C\uDFE5',
    headerColor: 'text-blue-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><FacilityManagementPanel /></Suspense>,
    category: 'admin',
    priority: 'high',
    roles: ['admin', 'super_admin', 'system_admin'],
  },
  {
    id: 'module-configuration',
    title: 'Module Configuration',
    subtitle: 'Enable or disable platform modules for your organization',
    icon: '\u2699\uFE0F',
    headerColor: 'text-teal-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><TenantModuleConfigPanel /></Suspense>,
    category: 'admin',
    priority: 'high',
    roles: ['admin', 'super_admin', 'system_admin'],
  },
  {
    id: 'clearinghouse-config',
    title: 'EDI Clearinghouse Configuration',
    subtitle: 'Configure credentials for Waystar, Change Healthcare, or Availity clearinghouse integration',
    icon: '\uD83D\uDD17',
    headerColor: 'text-indigo-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ClearinghouseConfigPanel /></Suspense>,
    category: 'admin',
    priority: 'medium',
    roles: ['admin', 'super_admin'],
  },
  {
    id: 'data-export',
    title: 'Data Export & Advanced Tools',
    subtitle: 'Export data and access advanced administrative functions',
    icon: '\uD83D\uDCE4',
    headerColor: 'text-gray-800',
    component: <Suspense fallback={<SectionLoadingFallback />}><ExportCheckIns /></Suspense>,
    category: 'admin',
    priority: 'low',
  },
];

/**
 * Get sections filtered by category
 */
export const getSectionsByCategory = (category: DashboardSection['category']): DashboardSection[] => {
  return getAllSections().filter(section => section.category === category);
};
