-- Add tenant_id to all remaining tables
BEGIN;

ALTER TABLE account_lockouts ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE admin_enroll_audit ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE admin_notes_audit ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE admin_role_pins ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE admin_sessions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE admin_settings ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE admin_usage_tracking ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE admin_user_questions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE ai_confidence_scores ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE ai_learning_milestones ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE ai_recording_analysis ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE anomaly_detections ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE app_owners ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE audit_phi_access ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE billing_payers ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE billing_providers ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE care_coordination_notes ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE care_team ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE care_team_members ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE caregiver_pin_attempts ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE caregiver_pins ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE caregiver_view_grants ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE ccm_time_tracking ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE check_ins_audit ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE chw_kiosk_devices ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE chw_kiosk_sessions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE chw_kiosk_usage_analytics ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE chw_patient_consent ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE claim_attachments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE claim_denials ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE claim_flag_types ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE claim_lines ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE claim_review_history ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE claim_status_history ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE claims ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE claude_admin_task_history ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE claude_admin_task_templates ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE claude_api_audit ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE claude_care_context ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE claude_translation_cache ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE claude_usage_logs ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE claude_voice_input_sessions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE clearinghouse_batch_items ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE clearinghouse_batches ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE clearinghouse_config ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE clinical_notes ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE cms_documentation ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE coding_audits ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE coding_recommendations ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE comment_reports ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE comments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE connection_pool_metrics ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE consent_expiration_alerts ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE cross_system_referrals ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE daily_behavior_summary ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE dashboard_personalization_events ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE data_retention_policies ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE denial_appeal_history ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE disaster_recovery_drills ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE discharge_plans ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE drill_checkpoints ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE drill_participants ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE drug_interaction_cache ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE drug_interaction_check_logs ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE ehr_observations ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE ehr_patient_mappings ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE ems_department_dispatches ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE ems_dispatch_protocols ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE ems_provider_signoffs ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE encounter_diagnoses ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE encounter_procedures ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE encryption_keys ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE enhanced_check_in_responses ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE fcm_tokens ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE feature_usage ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE fee_schedule_items ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE fee_schedule_rates ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE fee_schedules ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE fhir_care_team_members ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE fhir_care_teams ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE fhir_connections ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE fhir_encounters ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE fhir_immunizations ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE fhir_practitioner_roles ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE fhir_practitioners ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE fhir_procedures ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE fhir_questionnaires ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE field_visits ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE file_upload_audit ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE geofence_events ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE geofence_zones ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE guardian_alerts ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE guardian_eyes_recordings ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE handoff_attachments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE handoff_logs ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE hospital_departments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE interdisciplinary_care_teams ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE lab_results ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE login_attempts ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mcp_cache_performance ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mcp_cost_metrics ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE meal_interactions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE medication_doses_taken ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE medication_image_extractions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE medication_reminders ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE medications ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE memory_lane_trivia ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_account_lockouts_tenant_id ON account_lockouts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_admin_enroll_audit_tenant_id ON admin_enroll_audit(tenant_id);
CREATE INDEX IF NOT EXISTS idx_admin_notes_audit_tenant_id ON admin_notes_audit(tenant_id);
CREATE INDEX IF NOT EXISTS idx_admin_role_pins_tenant_id ON admin_role_pins(tenant_id);
CREATE INDEX IF NOT EXISTS idx_admin_sessions_tenant_id ON admin_sessions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_admin_settings_tenant_id ON admin_settings(tenant_id);
CREATE INDEX IF NOT EXISTS idx_admin_usage_tracking_tenant_id ON admin_usage_tracking(tenant_id);
CREATE INDEX IF NOT EXISTS idx_admin_user_questions_tenant_id ON admin_user_questions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ai_confidence_scores_tenant_id ON ai_confidence_scores(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ai_learning_milestones_tenant_id ON ai_learning_milestones(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ai_recording_analysis_tenant_id ON ai_recording_analysis(tenant_id);
CREATE INDEX IF NOT EXISTS idx_alerts_tenant_id ON alerts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_anomaly_detections_tenant_id ON anomaly_detections(tenant_id);
CREATE INDEX IF NOT EXISTS idx_api_keys_tenant_id ON api_keys(tenant_id);
CREATE INDEX IF NOT EXISTS idx_app_owners_tenant_id ON app_owners(tenant_id);
CREATE INDEX IF NOT EXISTS idx_audit_phi_access_tenant_id ON audit_phi_access(tenant_id);
CREATE INDEX IF NOT EXISTS idx_billing_payers_tenant_id ON billing_payers(tenant_id);
CREATE INDEX IF NOT EXISTS idx_billing_providers_tenant_id ON billing_providers(tenant_id);
CREATE INDEX IF NOT EXISTS idx_care_coordination_notes_tenant_id ON care_coordination_notes(tenant_id);
CREATE INDEX IF NOT EXISTS idx_care_team_tenant_id ON care_team(tenant_id);
CREATE INDEX IF NOT EXISTS idx_care_team_members_tenant_id ON care_team_members(tenant_id);
CREATE INDEX IF NOT EXISTS idx_caregiver_pin_attempts_tenant_id ON caregiver_pin_attempts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_caregiver_pins_tenant_id ON caregiver_pins(tenant_id);
CREATE INDEX IF NOT EXISTS idx_caregiver_view_grants_tenant_id ON caregiver_view_grants(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ccm_time_tracking_tenant_id ON ccm_time_tracking(tenant_id);
CREATE INDEX IF NOT EXISTS idx_check_ins_audit_tenant_id ON check_ins_audit(tenant_id);
CREATE INDEX IF NOT EXISTS idx_chw_kiosk_devices_tenant_id ON chw_kiosk_devices(tenant_id);
CREATE INDEX IF NOT EXISTS idx_chw_kiosk_sessions_tenant_id ON chw_kiosk_sessions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_chw_kiosk_usage_analytics_tenant_id ON chw_kiosk_usage_analytics(tenant_id);
CREATE INDEX IF NOT EXISTS idx_chw_patient_consent_tenant_id ON chw_patient_consent(tenant_id);
CREATE INDEX IF NOT EXISTS idx_claim_attachments_tenant_id ON claim_attachments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_claim_denials_tenant_id ON claim_denials(tenant_id);
CREATE INDEX IF NOT EXISTS idx_claim_flag_types_tenant_id ON claim_flag_types(tenant_id);
CREATE INDEX IF NOT EXISTS idx_claim_lines_tenant_id ON claim_lines(tenant_id);
CREATE INDEX IF NOT EXISTS idx_claim_review_history_tenant_id ON claim_review_history(tenant_id);
CREATE INDEX IF NOT EXISTS idx_claim_status_history_tenant_id ON claim_status_history(tenant_id);
CREATE INDEX IF NOT EXISTS idx_claims_tenant_id ON claims(tenant_id);
CREATE INDEX IF NOT EXISTS idx_claude_admin_task_history_tenant_id ON claude_admin_task_history(tenant_id);
CREATE INDEX IF NOT EXISTS idx_claude_admin_task_templates_tenant_id ON claude_admin_task_templates(tenant_id);
CREATE INDEX IF NOT EXISTS idx_claude_api_audit_tenant_id ON claude_api_audit(tenant_id);
CREATE INDEX IF NOT EXISTS idx_claude_care_context_tenant_id ON claude_care_context(tenant_id);
CREATE INDEX IF NOT EXISTS idx_claude_translation_cache_tenant_id ON claude_translation_cache(tenant_id);
CREATE INDEX IF NOT EXISTS idx_claude_usage_logs_tenant_id ON claude_usage_logs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_claude_voice_input_sessions_tenant_id ON claude_voice_input_sessions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_clearinghouse_batch_items_tenant_id ON clearinghouse_batch_items(tenant_id);
CREATE INDEX IF NOT EXISTS idx_clearinghouse_batches_tenant_id ON clearinghouse_batches(tenant_id);
CREATE INDEX IF NOT EXISTS idx_clearinghouse_config_tenant_id ON clearinghouse_config(tenant_id);
CREATE INDEX IF NOT EXISTS idx_clinical_notes_tenant_id ON clinical_notes(tenant_id);
CREATE INDEX IF NOT EXISTS idx_cms_documentation_tenant_id ON cms_documentation(tenant_id);
CREATE INDEX IF NOT EXISTS idx_coding_audits_tenant_id ON coding_audits(tenant_id);
CREATE INDEX IF NOT EXISTS idx_coding_recommendations_tenant_id ON coding_recommendations(tenant_id);
CREATE INDEX IF NOT EXISTS idx_comment_reports_tenant_id ON comment_reports(tenant_id);
CREATE INDEX IF NOT EXISTS idx_comments_tenant_id ON comments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_connection_pool_metrics_tenant_id ON connection_pool_metrics(tenant_id);
CREATE INDEX IF NOT EXISTS idx_consent_expiration_alerts_tenant_id ON consent_expiration_alerts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_cross_system_referrals_tenant_id ON cross_system_referrals(tenant_id);
CREATE INDEX IF NOT EXISTS idx_daily_behavior_summary_tenant_id ON daily_behavior_summary(tenant_id);
CREATE INDEX IF NOT EXISTS idx_dashboard_personalization_events_tenant_id ON dashboard_personalization_events(tenant_id);
CREATE INDEX IF NOT EXISTS idx_data_retention_policies_tenant_id ON data_retention_policies(tenant_id);
CREATE INDEX IF NOT EXISTS idx_denial_appeal_history_tenant_id ON denial_appeal_history(tenant_id);
CREATE INDEX IF NOT EXISTS idx_disaster_recovery_drills_tenant_id ON disaster_recovery_drills(tenant_id);
CREATE INDEX IF NOT EXISTS idx_discharge_plans_tenant_id ON discharge_plans(tenant_id);
CREATE INDEX IF NOT EXISTS idx_drill_checkpoints_tenant_id ON drill_checkpoints(tenant_id);
CREATE INDEX IF NOT EXISTS idx_drill_participants_tenant_id ON drill_participants(tenant_id);
CREATE INDEX IF NOT EXISTS idx_drug_interaction_cache_tenant_id ON drug_interaction_cache(tenant_id);
CREATE INDEX IF NOT EXISTS idx_drug_interaction_check_logs_tenant_id ON drug_interaction_check_logs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ehr_observations_tenant_id ON ehr_observations(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ehr_patient_mappings_tenant_id ON ehr_patient_mappings(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ems_department_dispatches_tenant_id ON ems_department_dispatches(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ems_dispatch_protocols_tenant_id ON ems_dispatch_protocols(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ems_provider_signoffs_tenant_id ON ems_provider_signoffs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_encounter_diagnoses_tenant_id ON encounter_diagnoses(tenant_id);
CREATE INDEX IF NOT EXISTS idx_encounter_procedures_tenant_id ON encounter_procedures(tenant_id);
CREATE INDEX IF NOT EXISTS idx_encryption_keys_tenant_id ON encryption_keys(tenant_id);
CREATE INDEX IF NOT EXISTS idx_enhanced_check_in_responses_tenant_id ON enhanced_check_in_responses(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fcm_tokens_tenant_id ON fcm_tokens(tenant_id);
CREATE INDEX IF NOT EXISTS idx_feature_usage_tenant_id ON feature_usage(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fee_schedule_items_tenant_id ON fee_schedule_items(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fee_schedule_rates_tenant_id ON fee_schedule_rates(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fee_schedules_tenant_id ON fee_schedules(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fhir_care_team_members_tenant_id ON fhir_care_team_members(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fhir_care_teams_tenant_id ON fhir_care_teams(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fhir_connections_tenant_id ON fhir_connections(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fhir_encounters_tenant_id ON fhir_encounters(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fhir_immunizations_tenant_id ON fhir_immunizations(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fhir_practitioner_roles_tenant_id ON fhir_practitioner_roles(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fhir_practitioners_tenant_id ON fhir_practitioners(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fhir_procedures_tenant_id ON fhir_procedures(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fhir_questionnaires_tenant_id ON fhir_questionnaires(tenant_id);
CREATE INDEX IF NOT EXISTS idx_field_visits_tenant_id ON field_visits(tenant_id);
CREATE INDEX IF NOT EXISTS idx_file_upload_audit_tenant_id ON file_upload_audit(tenant_id);
CREATE INDEX IF NOT EXISTS idx_geofence_events_tenant_id ON geofence_events(tenant_id);
CREATE INDEX IF NOT EXISTS idx_geofence_zones_tenant_id ON geofence_zones(tenant_id);
CREATE INDEX IF NOT EXISTS idx_guardian_alerts_tenant_id ON guardian_alerts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_guardian_eyes_recordings_tenant_id ON guardian_eyes_recordings(tenant_id);
CREATE INDEX IF NOT EXISTS idx_handoff_attachments_tenant_id ON handoff_attachments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_handoff_logs_tenant_id ON handoff_logs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_hospital_departments_tenant_id ON hospital_departments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_interdisciplinary_care_teams_tenant_id ON interdisciplinary_care_teams(tenant_id);
CREATE INDEX IF NOT EXISTS idx_lab_results_tenant_id ON lab_results(tenant_id);
CREATE INDEX IF NOT EXISTS idx_login_attempts_tenant_id ON login_attempts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mcp_cache_performance_tenant_id ON mcp_cache_performance(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mcp_cost_metrics_tenant_id ON mcp_cost_metrics(tenant_id);
CREATE INDEX IF NOT EXISTS idx_meal_interactions_tenant_id ON meal_interactions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_medication_doses_taken_tenant_id ON medication_doses_taken(tenant_id);
CREATE INDEX IF NOT EXISTS idx_medication_image_extractions_tenant_id ON medication_image_extractions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_medication_reminders_tenant_id ON medication_reminders(tenant_id);
CREATE INDEX IF NOT EXISTS idx_medications_tenant_id ON medications(tenant_id);
CREATE INDEX IF NOT EXISTS idx_memory_lane_trivia_tenant_id ON memory_lane_trivia(tenant_id);

-- Backfill
DO $$
DECLARE default_tenant UUID;
BEGIN
  SELECT id INTO default_tenant FROM tenants WHERE subdomain = 'www' LIMIT 1;
  UPDATE account_lockouts SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE admin_enroll_audit SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE admin_notes_audit SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE admin_role_pins SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE admin_sessions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE admin_settings SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE admin_usage_tracking SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE admin_user_questions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE ai_confidence_scores SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE ai_learning_milestones SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE ai_recording_analysis SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE alerts SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE anomaly_detections SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE api_keys SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE app_owners SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE audit_phi_access SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE billing_payers SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE billing_providers SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE care_coordination_notes SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE care_team SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE care_team_members SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE caregiver_pin_attempts SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE caregiver_pins SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE caregiver_view_grants SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE ccm_time_tracking SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE check_ins_audit SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE chw_kiosk_devices SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE chw_kiosk_sessions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE chw_kiosk_usage_analytics SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE chw_patient_consent SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE claim_attachments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE claim_denials SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE claim_flag_types SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE claim_lines SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE claim_review_history SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE claim_status_history SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE claims SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE claude_admin_task_history SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE claude_admin_task_templates SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE claude_api_audit SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE claude_care_context SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE claude_translation_cache SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE claude_usage_logs SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE claude_voice_input_sessions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE clearinghouse_batch_items SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE clearinghouse_batches SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE clearinghouse_config SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE clinical_notes SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE cms_documentation SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE coding_audits SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE coding_recommendations SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE comment_reports SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE comments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE connection_pool_metrics SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE consent_expiration_alerts SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE cross_system_referrals SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE daily_behavior_summary SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE dashboard_personalization_events SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE data_retention_policies SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE denial_appeal_history SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE disaster_recovery_drills SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE discharge_plans SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE drill_checkpoints SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE drill_participants SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE drug_interaction_cache SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE drug_interaction_check_logs SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE ehr_observations SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE ehr_patient_mappings SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE ems_department_dispatches SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE ems_dispatch_protocols SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE ems_provider_signoffs SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE encounter_diagnoses SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE encounter_procedures SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE encryption_keys SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE enhanced_check_in_responses SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE fcm_tokens SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE feature_usage SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE fee_schedule_items SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE fee_schedule_rates SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE fee_schedules SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE fhir_care_team_members SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE fhir_care_teams SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE fhir_connections SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE fhir_encounters SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE fhir_immunizations SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE fhir_practitioner_roles SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE fhir_practitioners SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE fhir_procedures SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE fhir_questionnaires SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE field_visits SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE file_upload_audit SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE geofence_events SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE geofence_zones SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE guardian_alerts SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE guardian_eyes_recordings SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE handoff_attachments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE handoff_logs SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE hospital_departments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE interdisciplinary_care_teams SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE lab_results SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE login_attempts SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mcp_cache_performance SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mcp_cost_metrics SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE meal_interactions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE medication_doses_taken SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE medication_image_extractions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE medication_reminders SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE medications SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE memory_lane_trivia SET tenant_id = default_tenant WHERE tenant_id IS NULL;
END$$;

COMMIT;
