-- Add tenant_id to all remaining tables
BEGIN;

ALTER TABLE mental_health_discharge_checklist ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mental_health_escalations ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mental_health_flags ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mental_health_quality_metrics ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mental_health_risk_assessments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mental_health_safety_plans ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mental_health_screening_triggers ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mental_health_service_requests ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mental_health_therapy_sessions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mental_health_trigger_conditions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mfa_enrollment ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mh_wearable_biomarkers ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mobile_devices ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mobile_emergency_contacts ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mobile_emergency_incidents ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mobile_sync_status ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE mobile_vitals ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE motivational_quotes ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE movement_patterns ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE neuro_barthel_index ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE neuro_care_plans ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE neuro_caregiver_assessments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE neuro_cognitive_assessments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE neuro_dementia_staging ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE neuro_modified_rankin_scale ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE neuro_stroke_assessments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE nurseos_feature_flags ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE nurseos_product_config ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE parkinsons_dbs_sessions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE parkinsons_forbes_tracking ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE parkinsons_medications ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE parkinsons_patients ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE parkinsons_robert_tracking ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE parkinsons_symptom_diary ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE parkinsons_updrs_assessments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE password_history ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE patient_admissions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE patient_daily_check_ins ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE patient_locations ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE peer_group_statistics ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE pending_registrations ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE penetration_test_executions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE performance_metrics ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE phi_access_logs ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE physician_section_interactions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE physician_workflow_preferences ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE post_acute_facilities ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE post_discharge_follow_ups ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE prehospital_handoffs ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE privacy_consent ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE provider_burnout_assessments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE provider_daily_checkins ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE provider_scribe_preferences ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE provider_support_circle_members ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE provider_support_circles ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE provider_support_reflections ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE provider_training_completions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE provider_voice_profiles ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE pt_exercise_library ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE pt_functional_assessments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE pt_home_exercise_programs ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE pt_outcome_measures ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE pt_quality_metrics ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE pt_team_communications ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE pt_telehealth_sessions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE pt_treatment_plans ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE pt_treatment_sessions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE pt_wearable_enhanced_outcomes ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE push_subscriptions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE query_result_cache ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE question_assignments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE question_templates ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE questionnaire_analytics ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE questionnaire_deployments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE questionnaire_responses ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE questionnaire_templates ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE rate_limit_admin ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE rate_limit_attempts ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE rate_limit_logins ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE rate_limit_registrations ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE realtime_subscription_registry ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE referral_auto_creation_rules ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE remittances ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE resilience_resources ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE resilience_training_modules ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE resilience_training_progress ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE risk_assessments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE rls_policy_audit ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE scribe_conversation_context ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE scribe_interaction_history ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE sdoh_assessments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE security_alerts ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE security_events ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE security_notifications ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE security_vulnerabilities ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE self_report_submissions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE self_reports ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE senior_demographics ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE senior_emergency_contacts ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE senior_health ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE senior_sdoh ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE session_recordings ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE shift_handoff_events ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE shift_handoff_overrides ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE shift_handoff_risk_scores ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE specialist_alerts ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE specialist_assessments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE specialist_providers ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE staff_auth_attempts ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE staff_pins ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE system_health ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE system_recordings ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE telehealth_appointments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE telehealth_session_events ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE telehealth_sessions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE trivia_game_results ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE unified_care_plan_links ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE user_behavior_profiles ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE user_geolocation_history ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE user_greeting_preferences ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE user_questions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE user_roles_audit ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE user_sessions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE user_trivia_progress ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE user_trivia_trophies ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE voice_profiles ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE wearable_activity_data ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE wearable_connections ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE wearable_fall_detections ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE wearable_gait_analysis ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE wearable_vital_signs ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE wellness_enrollments ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE word_game_results ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE RESTRICT;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_mental_health_discharge_checklist_tenant_id ON mental_health_discharge_checklist(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mental_health_escalations_tenant_id ON mental_health_escalations(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mental_health_flags_tenant_id ON mental_health_flags(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mental_health_quality_metrics_tenant_id ON mental_health_quality_metrics(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mental_health_risk_assessments_tenant_id ON mental_health_risk_assessments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mental_health_safety_plans_tenant_id ON mental_health_safety_plans(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mental_health_screening_triggers_tenant_id ON mental_health_screening_triggers(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mental_health_service_requests_tenant_id ON mental_health_service_requests(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mental_health_therapy_sessions_tenant_id ON mental_health_therapy_sessions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mental_health_trigger_conditions_tenant_id ON mental_health_trigger_conditions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mfa_enrollment_tenant_id ON mfa_enrollment(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mh_wearable_biomarkers_tenant_id ON mh_wearable_biomarkers(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mobile_devices_tenant_id ON mobile_devices(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mobile_emergency_contacts_tenant_id ON mobile_emergency_contacts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mobile_emergency_incidents_tenant_id ON mobile_emergency_incidents(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mobile_sync_status_tenant_id ON mobile_sync_status(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mobile_vitals_tenant_id ON mobile_vitals(tenant_id);
CREATE INDEX IF NOT EXISTS idx_motivational_quotes_tenant_id ON motivational_quotes(tenant_id);
CREATE INDEX IF NOT EXISTS idx_movement_patterns_tenant_id ON movement_patterns(tenant_id);
CREATE INDEX IF NOT EXISTS idx_neuro_barthel_index_tenant_id ON neuro_barthel_index(tenant_id);
CREATE INDEX IF NOT EXISTS idx_neuro_care_plans_tenant_id ON neuro_care_plans(tenant_id);
CREATE INDEX IF NOT EXISTS idx_neuro_caregiver_assessments_tenant_id ON neuro_caregiver_assessments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_neuro_cognitive_assessments_tenant_id ON neuro_cognitive_assessments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_neuro_dementia_staging_tenant_id ON neuro_dementia_staging(tenant_id);
CREATE INDEX IF NOT EXISTS idx_neuro_modified_rankin_scale_tenant_id ON neuro_modified_rankin_scale(tenant_id);
CREATE INDEX IF NOT EXISTS idx_neuro_stroke_assessments_tenant_id ON neuro_stroke_assessments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_nurseos_feature_flags_tenant_id ON nurseos_feature_flags(tenant_id);
CREATE INDEX IF NOT EXISTS idx_nurseos_product_config_tenant_id ON nurseos_product_config(tenant_id);
CREATE INDEX IF NOT EXISTS idx_parkinsons_dbs_sessions_tenant_id ON parkinsons_dbs_sessions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_parkinsons_forbes_tracking_tenant_id ON parkinsons_forbes_tracking(tenant_id);
CREATE INDEX IF NOT EXISTS idx_parkinsons_medications_tenant_id ON parkinsons_medications(tenant_id);
CREATE INDEX IF NOT EXISTS idx_parkinsons_patients_tenant_id ON parkinsons_patients(tenant_id);
CREATE INDEX IF NOT EXISTS idx_parkinsons_robert_tracking_tenant_id ON parkinsons_robert_tracking(tenant_id);
CREATE INDEX IF NOT EXISTS idx_parkinsons_symptom_diary_tenant_id ON parkinsons_symptom_diary(tenant_id);
CREATE INDEX IF NOT EXISTS idx_parkinsons_updrs_assessments_tenant_id ON parkinsons_updrs_assessments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_password_history_tenant_id ON password_history(tenant_id);
CREATE INDEX IF NOT EXISTS idx_patient_admissions_tenant_id ON patient_admissions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_patient_daily_check_ins_tenant_id ON patient_daily_check_ins(tenant_id);
CREATE INDEX IF NOT EXISTS idx_patient_locations_tenant_id ON patient_locations(tenant_id);
CREATE INDEX IF NOT EXISTS idx_peer_group_statistics_tenant_id ON peer_group_statistics(tenant_id);
CREATE INDEX IF NOT EXISTS idx_pending_registrations_tenant_id ON pending_registrations(tenant_id);
CREATE INDEX IF NOT EXISTS idx_penetration_test_executions_tenant_id ON penetration_test_executions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_performance_metrics_tenant_id ON performance_metrics(tenant_id);
CREATE INDEX IF NOT EXISTS idx_phi_access_logs_tenant_id ON phi_access_logs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_physician_section_interactions_tenant_id ON physician_section_interactions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_physician_workflow_preferences_tenant_id ON physician_workflow_preferences(tenant_id);
CREATE INDEX IF NOT EXISTS idx_post_acute_facilities_tenant_id ON post_acute_facilities(tenant_id);
CREATE INDEX IF NOT EXISTS idx_post_discharge_follow_ups_tenant_id ON post_discharge_follow_ups(tenant_id);
CREATE INDEX IF NOT EXISTS idx_prehospital_handoffs_tenant_id ON prehospital_handoffs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_privacy_consent_tenant_id ON privacy_consent(tenant_id);
CREATE INDEX IF NOT EXISTS idx_provider_burnout_assessments_tenant_id ON provider_burnout_assessments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_provider_daily_checkins_tenant_id ON provider_daily_checkins(tenant_id);
CREATE INDEX IF NOT EXISTS idx_provider_scribe_preferences_tenant_id ON provider_scribe_preferences(tenant_id);
CREATE INDEX IF NOT EXISTS idx_provider_support_circle_members_tenant_id ON provider_support_circle_members(tenant_id);
CREATE INDEX IF NOT EXISTS idx_provider_support_circles_tenant_id ON provider_support_circles(tenant_id);
CREATE INDEX IF NOT EXISTS idx_provider_support_reflections_tenant_id ON provider_support_reflections(tenant_id);
CREATE INDEX IF NOT EXISTS idx_provider_training_completions_tenant_id ON provider_training_completions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_provider_voice_profiles_tenant_id ON provider_voice_profiles(tenant_id);
CREATE INDEX IF NOT EXISTS idx_pt_exercise_library_tenant_id ON pt_exercise_library(tenant_id);
CREATE INDEX IF NOT EXISTS idx_pt_functional_assessments_tenant_id ON pt_functional_assessments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_pt_home_exercise_programs_tenant_id ON pt_home_exercise_programs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_pt_outcome_measures_tenant_id ON pt_outcome_measures(tenant_id);
CREATE INDEX IF NOT EXISTS idx_pt_quality_metrics_tenant_id ON pt_quality_metrics(tenant_id);
CREATE INDEX IF NOT EXISTS idx_pt_team_communications_tenant_id ON pt_team_communications(tenant_id);
CREATE INDEX IF NOT EXISTS idx_pt_telehealth_sessions_tenant_id ON pt_telehealth_sessions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_pt_treatment_plans_tenant_id ON pt_treatment_plans(tenant_id);
CREATE INDEX IF NOT EXISTS idx_pt_treatment_sessions_tenant_id ON pt_treatment_sessions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_pt_wearable_enhanced_outcomes_tenant_id ON pt_wearable_enhanced_outcomes(tenant_id);
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_tenant_id ON push_subscriptions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_query_result_cache_tenant_id ON query_result_cache(tenant_id);
CREATE INDEX IF NOT EXISTS idx_question_assignments_tenant_id ON question_assignments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_question_templates_tenant_id ON question_templates(tenant_id);
CREATE INDEX IF NOT EXISTS idx_questionnaire_analytics_tenant_id ON questionnaire_analytics(tenant_id);
CREATE INDEX IF NOT EXISTS idx_questionnaire_deployments_tenant_id ON questionnaire_deployments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_questionnaire_responses_tenant_id ON questionnaire_responses(tenant_id);
CREATE INDEX IF NOT EXISTS idx_questionnaire_templates_tenant_id ON questionnaire_templates(tenant_id);
CREATE INDEX IF NOT EXISTS idx_rate_limit_admin_tenant_id ON rate_limit_admin(tenant_id);
CREATE INDEX IF NOT EXISTS idx_rate_limit_attempts_tenant_id ON rate_limit_attempts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_rate_limit_logins_tenant_id ON rate_limit_logins(tenant_id);
CREATE INDEX IF NOT EXISTS idx_rate_limit_registrations_tenant_id ON rate_limit_registrations(tenant_id);
CREATE INDEX IF NOT EXISTS idx_realtime_subscription_registry_tenant_id ON realtime_subscription_registry(tenant_id);
CREATE INDEX IF NOT EXISTS idx_referral_auto_creation_rules_tenant_id ON referral_auto_creation_rules(tenant_id);
CREATE INDEX IF NOT EXISTS idx_remittances_tenant_id ON remittances(tenant_id);
CREATE INDEX IF NOT EXISTS idx_resilience_resources_tenant_id ON resilience_resources(tenant_id);
CREATE INDEX IF NOT EXISTS idx_resilience_training_modules_tenant_id ON resilience_training_modules(tenant_id);
CREATE INDEX IF NOT EXISTS idx_resilience_training_progress_tenant_id ON resilience_training_progress(tenant_id);
CREATE INDEX IF NOT EXISTS idx_risk_assessments_tenant_id ON risk_assessments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_rls_policy_audit_tenant_id ON rls_policy_audit(tenant_id);
CREATE INDEX IF NOT EXISTS idx_roles_tenant_id ON roles(tenant_id);
CREATE INDEX IF NOT EXISTS idx_scribe_conversation_context_tenant_id ON scribe_conversation_context(tenant_id);
CREATE INDEX IF NOT EXISTS idx_scribe_interaction_history_tenant_id ON scribe_interaction_history(tenant_id);
CREATE INDEX IF NOT EXISTS idx_sdoh_assessments_tenant_id ON sdoh_assessments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_security_alerts_tenant_id ON security_alerts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_security_events_tenant_id ON security_events(tenant_id);
CREATE INDEX IF NOT EXISTS idx_security_notifications_tenant_id ON security_notifications(tenant_id);
CREATE INDEX IF NOT EXISTS idx_security_vulnerabilities_tenant_id ON security_vulnerabilities(tenant_id);
CREATE INDEX IF NOT EXISTS idx_self_report_submissions_tenant_id ON self_report_submissions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_self_reports_tenant_id ON self_reports(tenant_id);
CREATE INDEX IF NOT EXISTS idx_senior_demographics_tenant_id ON senior_demographics(tenant_id);
CREATE INDEX IF NOT EXISTS idx_senior_emergency_contacts_tenant_id ON senior_emergency_contacts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_senior_health_tenant_id ON senior_health(tenant_id);
CREATE INDEX IF NOT EXISTS idx_senior_sdoh_tenant_id ON senior_sdoh(tenant_id);
CREATE INDEX IF NOT EXISTS idx_session_recordings_tenant_id ON session_recordings(tenant_id);
CREATE INDEX IF NOT EXISTS idx_shift_handoff_events_tenant_id ON shift_handoff_events(tenant_id);
CREATE INDEX IF NOT EXISTS idx_shift_handoff_overrides_tenant_id ON shift_handoff_overrides(tenant_id);
CREATE INDEX IF NOT EXISTS idx_shift_handoff_risk_scores_tenant_id ON shift_handoff_risk_scores(tenant_id);
CREATE INDEX IF NOT EXISTS idx_specialist_alerts_tenant_id ON specialist_alerts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_specialist_assessments_tenant_id ON specialist_assessments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_specialist_providers_tenant_id ON specialist_providers(tenant_id);
CREATE INDEX IF NOT EXISTS idx_staff_auth_attempts_tenant_id ON staff_auth_attempts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_staff_pins_tenant_id ON staff_pins(tenant_id);
CREATE INDEX IF NOT EXISTS idx_system_health_tenant_id ON system_health(tenant_id);
CREATE INDEX IF NOT EXISTS idx_system_recordings_tenant_id ON system_recordings(tenant_id);
CREATE INDEX IF NOT EXISTS idx_telehealth_appointments_tenant_id ON telehealth_appointments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_telehealth_session_events_tenant_id ON telehealth_session_events(tenant_id);
CREATE INDEX IF NOT EXISTS idx_telehealth_sessions_tenant_id ON telehealth_sessions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_trivia_game_results_tenant_id ON trivia_game_results(tenant_id);
CREATE INDEX IF NOT EXISTS idx_unified_care_plan_links_tenant_id ON unified_care_plan_links(tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_behavior_profiles_tenant_id ON user_behavior_profiles(tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_geolocation_history_tenant_id ON user_geolocation_history(tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_greeting_preferences_tenant_id ON user_greeting_preferences(tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_questions_tenant_id ON user_questions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_audit_tenant_id ON user_roles_audit(tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_tenant_id ON user_sessions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_trivia_progress_tenant_id ON user_trivia_progress(tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_trivia_trophies_tenant_id ON user_trivia_trophies(tenant_id);
CREATE INDEX IF NOT EXISTS idx_voice_profiles_tenant_id ON voice_profiles(tenant_id);
CREATE INDEX IF NOT EXISTS idx_wearable_activity_data_tenant_id ON wearable_activity_data(tenant_id);
CREATE INDEX IF NOT EXISTS idx_wearable_connections_tenant_id ON wearable_connections(tenant_id);
CREATE INDEX IF NOT EXISTS idx_wearable_fall_detections_tenant_id ON wearable_fall_detections(tenant_id);
CREATE INDEX IF NOT EXISTS idx_wearable_gait_analysis_tenant_id ON wearable_gait_analysis(tenant_id);
CREATE INDEX IF NOT EXISTS idx_wearable_vital_signs_tenant_id ON wearable_vital_signs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_wellness_enrollments_tenant_id ON wellness_enrollments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_word_game_results_tenant_id ON word_game_results(tenant_id);

-- Backfill
DO $$
DECLARE default_tenant UUID;
BEGIN
  SELECT id INTO default_tenant FROM tenants WHERE subdomain = 'www' LIMIT 1;
  UPDATE mental_health_discharge_checklist SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mental_health_escalations SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mental_health_flags SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mental_health_quality_metrics SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mental_health_risk_assessments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mental_health_safety_plans SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mental_health_screening_triggers SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mental_health_service_requests SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mental_health_therapy_sessions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mental_health_trigger_conditions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mfa_enrollment SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mh_wearable_biomarkers SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mobile_devices SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mobile_emergency_contacts SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mobile_emergency_incidents SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mobile_sync_status SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE mobile_vitals SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE motivational_quotes SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE movement_patterns SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE neuro_barthel_index SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE neuro_care_plans SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE neuro_caregiver_assessments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE neuro_cognitive_assessments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE neuro_dementia_staging SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE neuro_modified_rankin_scale SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE neuro_stroke_assessments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE nurseos_feature_flags SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE nurseos_product_config SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE parkinsons_dbs_sessions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE parkinsons_forbes_tracking SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE parkinsons_medications SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE parkinsons_patients SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE parkinsons_robert_tracking SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE parkinsons_symptom_diary SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE parkinsons_updrs_assessments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE password_history SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE patient_admissions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE patient_daily_check_ins SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE patient_locations SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE peer_group_statistics SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE pending_registrations SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE penetration_test_executions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE performance_metrics SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE phi_access_logs SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE physician_section_interactions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE physician_workflow_preferences SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE post_acute_facilities SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE post_discharge_follow_ups SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE prehospital_handoffs SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE privacy_consent SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE provider_burnout_assessments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE provider_daily_checkins SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE provider_scribe_preferences SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE provider_support_circle_members SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE provider_support_circles SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE provider_support_reflections SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE provider_training_completions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE provider_voice_profiles SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE pt_exercise_library SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE pt_functional_assessments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE pt_home_exercise_programs SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE pt_outcome_measures SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE pt_quality_metrics SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE pt_team_communications SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE pt_telehealth_sessions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE pt_treatment_plans SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE pt_treatment_sessions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE pt_wearable_enhanced_outcomes SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE push_subscriptions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE query_result_cache SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE question_assignments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE question_templates SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE questionnaire_analytics SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE questionnaire_deployments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE questionnaire_responses SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE questionnaire_templates SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE rate_limit_admin SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE rate_limit_attempts SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE rate_limit_logins SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE rate_limit_registrations SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE realtime_subscription_registry SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE referral_auto_creation_rules SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE remittances SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE resilience_resources SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE resilience_training_modules SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE resilience_training_progress SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE risk_assessments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE rls_policy_audit SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE roles SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE scribe_conversation_context SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE scribe_interaction_history SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE sdoh_assessments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE security_alerts SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE security_events SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE security_notifications SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE security_vulnerabilities SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE self_report_submissions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE self_reports SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE senior_demographics SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE senior_emergency_contacts SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE senior_health SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE senior_sdoh SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE session_recordings SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE shift_handoff_events SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE shift_handoff_overrides SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE shift_handoff_risk_scores SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE specialist_alerts SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE specialist_assessments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE specialist_providers SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE staff_auth_attempts SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE staff_pins SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE system_health SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE system_recordings SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE telehealth_appointments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE telehealth_session_events SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE telehealth_sessions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE trivia_game_results SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE unified_care_plan_links SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE user_behavior_profiles SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE user_geolocation_history SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE user_greeting_preferences SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE user_questions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE user_roles_audit SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE user_sessions SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE user_trivia_progress SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE user_trivia_trophies SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE voice_profiles SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE wearable_activity_data SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE wearable_connections SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE wearable_fall_detections SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE wearable_gait_analysis SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE wearable_vital_signs SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE wellness_enrollments SET tenant_id = default_tenant WHERE tenant_id IS NULL;
  UPDATE word_game_results SET tenant_id = default_tenant WHERE tenant_id IS NULL;
END$$;

COMMIT;
