-- =============================================================================
-- Encounter Visit State Machine
-- =============================================================================
-- Purpose: Replace billing-only encounter statuses with a full clinical visit
--          lifecycle for doctor's office workflow.
--
-- States: draft → scheduled → arrived → triaged → in_progress →
--         ready_for_sign → signed → ready_for_billing → billed →
--         completed | cancelled | no_show
--
-- Immutability: Aligns with existing prevent_finalized_encounter_modification()
--               trigger (20260131160000). Editable states are:
--               draft, scheduled, arrived, triaged, in_progress, ready_for_sign
--
-- Audit: Every status change is recorded in encounter_status_history.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. Drop old billing-only CHECK constraint and add clinical states
-- =============================================================================

-- The original constraint was: CHECK (status IN ('draft','ready','submitted','paid','denied'))
-- Drop it safely (constraint name auto-generated by Postgres as encounters_status_check)
ALTER TABLE public.encounters
  DROP CONSTRAINT IF EXISTS encounters_status_check;

-- Add the new clinical visit lifecycle states
ALTER TABLE public.encounters
  ADD CONSTRAINT encounters_status_check CHECK (status IN (
    'draft',              -- Encounter created manually, not yet scheduled
    'scheduled',          -- Linked to appointment, patient not yet arrived
    'arrived',            -- Patient checked in at front desk
    'triaged',            -- Vitals taken, patient roomed by nurse
    'in_progress',        -- Provider is seeing the patient
    'ready_for_sign',     -- Visit documented, awaiting provider signature
    'signed',             -- Provider signed/attested the documentation
    'ready_for_billing',  -- Coding confirmed, ready for claim generation
    'billed',             -- Claim generated and submitted
    'completed',          -- Fully resolved (paid, closed, or finalized)
    'cancelled',          -- Visit was cancelled before completion
    'no_show'             -- Patient did not show up
  ));

-- =============================================================================
-- 2. Add clinical workflow columns to encounters (IF NOT EXISTS)
-- =============================================================================

-- Encounter type (already exists in production via direct SQL, formalize here)
ALTER TABLE public.encounters
  ADD COLUMN IF NOT EXISTS encounter_type TEXT DEFAULT 'office_visit'
  CHECK (encounter_type IN (
    'office_visit', 'follow_up', 'new_patient', 'annual_wellness',
    'urgent', 'telehealth', 'procedure', 'consultation', 'pre_op', 'post_op'
  ));

-- Chief complaint (already exists in production via direct SQL, formalize here)
ALTER TABLE public.encounters
  ADD COLUMN IF NOT EXISTS chief_complaint TEXT;

-- Status tracking columns for audit
ALTER TABLE public.encounters
  ADD COLUMN IF NOT EXISTS status_changed_at TIMESTAMPTZ DEFAULT now();

ALTER TABLE public.encounters
  ADD COLUMN IF NOT EXISTS status_changed_by UUID REFERENCES auth.users(id);

-- Appointment linkage
ALTER TABLE public.encounters
  ADD COLUMN IF NOT EXISTS appointment_id UUID;

-- Visit timing
ALTER TABLE public.encounters
  ADD COLUMN IF NOT EXISTS arrived_at TIMESTAMPTZ;

ALTER TABLE public.encounters
  ADD COLUMN IF NOT EXISTS triaged_at TIMESTAMPTZ;

ALTER TABLE public.encounters
  ADD COLUMN IF NOT EXISTS visit_started_at TIMESTAMPTZ;

ALTER TABLE public.encounters
  ADD COLUMN IF NOT EXISTS visit_ended_at TIMESTAMPTZ;

ALTER TABLE public.encounters
  ADD COLUMN IF NOT EXISTS signed_at TIMESTAMPTZ;

ALTER TABLE public.encounters
  ADD COLUMN IF NOT EXISTS signed_by UUID REFERENCES auth.users(id);

-- Indexes for new columns
CREATE INDEX IF NOT EXISTS idx_encounters_encounter_type
  ON public.encounters(encounter_type);
CREATE INDEX IF NOT EXISTS idx_encounters_status_changed_at
  ON public.encounters(status_changed_at);
CREATE INDEX IF NOT EXISTS idx_encounters_appointment_id
  ON public.encounters(appointment_id);

-- =============================================================================
-- 3. Encounter Status History (audit table)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.encounter_status_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  encounter_id UUID NOT NULL REFERENCES public.encounters(id) ON DELETE CASCADE,
  from_status TEXT,
  to_status TEXT NOT NULL,
  changed_by UUID REFERENCES auth.users(id),
  changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reason TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_encounter_status_history_encounter
  ON public.encounter_status_history(encounter_id);
CREATE INDEX IF NOT EXISTS idx_encounter_status_history_changed_at
  ON public.encounter_status_history(changed_at);
CREATE INDEX IF NOT EXISTS idx_encounter_status_history_tenant
  ON public.encounter_status_history(tenant_id);

ALTER TABLE public.encounter_status_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "encounter_status_history_admin_read" ON public.encounter_status_history;
CREATE POLICY "encounter_status_history_admin_read" ON public.encounter_status_history
  FOR SELECT
  USING (public.is_admin(auth.uid()));

DROP POLICY IF EXISTS "encounter_status_history_admin_insert" ON public.encounter_status_history;
CREATE POLICY "encounter_status_history_admin_insert" ON public.encounter_status_history
  FOR INSERT
  WITH CHECK (public.is_admin(auth.uid()));

COMMENT ON TABLE public.encounter_status_history IS
  'Audit trail for encounter status transitions. Every state change is recorded.';

-- =============================================================================
-- 4. Valid Transition Map (reference table)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.encounter_valid_transitions (
  id SERIAL PRIMARY KEY,
  from_status TEXT NOT NULL,
  to_status TEXT NOT NULL,
  requires_role TEXT,  -- Optional: role required for this transition
  description TEXT,
  UNIQUE(from_status, to_status)
);

-- Populate the valid transitions
INSERT INTO public.encounter_valid_transitions (from_status, to_status, description) VALUES
  -- Forward flow
  ('draft',              'scheduled',          'Link encounter to appointment'),
  ('draft',              'arrived',            'Walk-in patient, skip scheduling'),
  ('draft',              'in_progress',        'Direct start (provider-initiated)'),
  ('draft',              'cancelled',          'Cancel before patient arrives'),
  ('scheduled',          'arrived',            'Patient checks in at front desk'),
  ('scheduled',          'cancelled',          'Cancel scheduled visit'),
  ('scheduled',          'no_show',            'Patient did not show up'),
  ('arrived',            'triaged',            'Nurse takes vitals and rooms patient'),
  ('arrived',            'cancelled',          'Cancel after arrival (patient leaves)'),
  ('triaged',            'in_progress',        'Provider begins seeing patient'),
  ('in_progress',        'ready_for_sign',     'Provider finishes documentation'),
  ('ready_for_sign',     'in_progress',        'Provider needs to add more notes'),
  ('ready_for_sign',     'signed',             'Provider signs/attests documentation'),
  ('signed',             'ready_for_billing',  'Coding confirmed by provider or coder'),
  ('signed',             'ready_for_sign',     'Unlock for correction before billing'),
  ('ready_for_billing',  'billed',             'Claim generated and submitted'),
  ('billed',             'completed',          'Payment received or claim closed')
ON CONFLICT (from_status, to_status) DO NOTHING;

-- =============================================================================
-- 5. Transition Validation Function
-- =============================================================================

CREATE OR REPLACE FUNCTION public.validate_encounter_transition(
  p_encounter_id UUID,
  p_new_status TEXT,
  p_changed_by UUID DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_current_status TEXT;
  v_tenant_id UUID;
  v_is_valid BOOLEAN;
BEGIN
  -- Get current encounter status
  SELECT status, tenant_id INTO v_current_status, v_tenant_id
  FROM encounters
  WHERE id = p_encounter_id;

  IF v_current_status IS NULL THEN
    RETURN jsonb_build_object(
      'valid', false,
      'error', 'Encounter not found',
      'code', 'ENCOUNTER_NOT_FOUND'
    );
  END IF;

  -- Same status is a no-op
  IF v_current_status = p_new_status THEN
    RETURN jsonb_build_object(
      'valid', true,
      'no_op', true,
      'message', 'Already in requested status'
    );
  END IF;

  -- Check if transition is valid
  SELECT EXISTS(
    SELECT 1 FROM encounter_valid_transitions
    WHERE from_status = v_current_status AND to_status = p_new_status
  ) INTO v_is_valid;

  IF NOT v_is_valid THEN
    RETURN jsonb_build_object(
      'valid', false,
      'error', format('Invalid transition: %s → %s', v_current_status, p_new_status),
      'code', 'INVALID_TRANSITION',
      'from_status', v_current_status,
      'to_status', p_new_status
    );
  END IF;

  RETURN jsonb_build_object(
    'valid', true,
    'from_status', v_current_status,
    'to_status', p_new_status,
    'tenant_id', v_tenant_id
  );
END;
$$;

-- =============================================================================
-- 6. Transition Execution Function (validates + transitions + audits)
-- =============================================================================

CREATE OR REPLACE FUNCTION public.transition_encounter_status(
  p_encounter_id UUID,
  p_new_status TEXT,
  p_changed_by UUID,
  p_reason TEXT DEFAULT NULL,
  p_metadata JSONB DEFAULT '{}'::jsonb
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_validation JSONB;
  v_current_status TEXT;
  v_tenant_id UUID;
  v_timestamp_col TEXT;
BEGIN
  -- Validate the transition
  v_validation := validate_encounter_transition(p_encounter_id, p_new_status, p_changed_by);

  IF NOT (v_validation->>'valid')::boolean THEN
    RETURN v_validation;
  END IF;

  -- Handle no-op
  IF (v_validation->>'no_op')::boolean IS TRUE THEN
    RETURN v_validation;
  END IF;

  v_current_status := v_validation->>'from_status';
  v_tenant_id := (v_validation->>'tenant_id')::uuid;

  -- Update the encounter status and tracking columns
  UPDATE encounters SET
    status = p_new_status,
    status_changed_at = now(),
    status_changed_by = p_changed_by,
    arrived_at = CASE WHEN p_new_status = 'arrived' THEN now() ELSE arrived_at END,
    triaged_at = CASE WHEN p_new_status = 'triaged' THEN now() ELSE triaged_at END,
    visit_started_at = CASE WHEN p_new_status = 'in_progress' THEN now() ELSE visit_started_at END,
    visit_ended_at = CASE WHEN p_new_status IN ('ready_for_sign', 'signed') THEN now() ELSE visit_ended_at END,
    signed_at = CASE WHEN p_new_status = 'signed' THEN now() ELSE signed_at END,
    signed_by = CASE WHEN p_new_status = 'signed' THEN p_changed_by ELSE signed_by END
  WHERE id = p_encounter_id;

  -- Record in status history
  INSERT INTO encounter_status_history (
    encounter_id, from_status, to_status, changed_by, reason, metadata, tenant_id
  ) VALUES (
    p_encounter_id, v_current_status, p_new_status, p_changed_by, p_reason, p_metadata, v_tenant_id
  );

  RETURN jsonb_build_object(
    'valid', true,
    'from_status', v_current_status,
    'to_status', p_new_status,
    'encounter_id', p_encounter_id,
    'changed_at', now()
  );
END;
$$;

-- =============================================================================
-- 7. Update Immutability Trigger (align with new states)
-- =============================================================================
-- The existing trigger (20260131160000) allows: draft, scheduled, in-progress, arrived, triaged
-- We need to add ready_for_sign since providers may still edit during that state

CREATE OR REPLACE FUNCTION prevent_finalized_encounter_modification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  -- Allow modifications while encounter is in editable states
  -- Status changes are handled by transition_encounter_status() which bypasses this
  IF OLD.status IN ('draft', 'scheduled', 'arrived', 'triaged', 'in_progress', 'ready_for_sign') THEN
    RETURN NEW;
  END IF;

  -- Allow ONLY status field changes on non-editable encounters
  -- (transition_encounter_status needs to update status on signed/billed encounters)
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    -- Verify only status-related columns changed
    IF NEW.notes IS NOT DISTINCT FROM OLD.notes
       AND NEW.chief_complaint IS NOT DISTINCT FROM OLD.chief_complaint
    THEN
      RETURN NEW;
    END IF;
  END IF;

  -- Block all other modifications to finalized encounters
  RAISE EXCEPTION '[CLINICAL_IMMUTABILITY_VIOLATION] Cannot % finalized encounter (status: %). Medical records are immutable after signing for HIPAA compliance.',
    TG_OP, OLD.status
    USING HINT = 'Encounters cannot be modified after status changes to signed/billed/completed. Use the amendment workflow instead.';

  RETURN NULL;
END;
$$;

-- =============================================================================
-- 8. Helper Views
-- =============================================================================

-- Editable state check (for service layer use)
CREATE OR REPLACE FUNCTION public.is_encounter_editable(p_encounter_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT status IN ('draft', 'scheduled', 'arrived', 'triaged', 'in_progress', 'ready_for_sign')
  FROM encounters
  WHERE id = p_encounter_id;
$$;

-- Get available transitions for an encounter
CREATE OR REPLACE FUNCTION public.get_encounter_available_transitions(p_encounter_id UUID)
RETURNS TABLE(to_status TEXT, description TEXT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT vt.to_status, vt.description
  FROM encounters e
  JOIN encounter_valid_transitions vt ON vt.from_status = e.status
  WHERE e.id = p_encounter_id
  ORDER BY vt.id;
$$;

-- =============================================================================
-- 9. Map existing data to new states
-- =============================================================================
-- 'ready' → 'ready_for_billing' (was: ready for claim submission)
-- 'submitted' → 'billed' (was: claim submitted)
-- 'paid' → 'completed' (was: claim paid)
-- 'denied' stays as 'denied' — but we need to handle it
-- Actually 'denied' is a claim status. Encounters with denied claims go back to
-- ready_for_billing for rebilling. For safety, map to 'completed' with a note.

UPDATE public.encounters SET status = 'ready_for_billing' WHERE status = 'ready';
UPDATE public.encounters SET status = 'billed' WHERE status = 'submitted';
UPDATE public.encounters SET status = 'completed' WHERE status = 'paid';
UPDATE public.encounters SET status = 'completed' WHERE status = 'denied';

-- =============================================================================
-- 10. Verification
-- =============================================================================

DO $$
DECLARE
  v_states TEXT[];
  v_transitions INTEGER;
  v_history_exists BOOLEAN;
BEGIN
  -- Verify all constraint states exist
  SELECT ARRAY(
    SELECT DISTINCT unnest(ARRAY[from_status, to_status])
    FROM encounter_valid_transitions
  ) INTO v_states;

  SELECT COUNT(*) INTO v_transitions FROM encounter_valid_transitions;

  SELECT EXISTS(
    SELECT 1 FROM information_schema.tables
    WHERE table_name = 'encounter_status_history'
  ) INTO v_history_exists;

  RAISE NOTICE 'Visit state machine migration complete:';
  RAISE NOTICE '  - % valid transitions defined', v_transitions;
  RAISE NOTICE '  - Status history table exists: %', v_history_exists;
  RAISE NOTICE '  - Immutability trigger updated with ready_for_sign as editable';
END $$;

COMMIT;
