-- =====================================================
-- L&D ALERTS — Persistent alert storage
-- =====================================================
-- Purpose: Store, acknowledge, and resolve clinical alerts
-- generated by the L&D module alert engine
-- =====================================================

CREATE TABLE IF NOT EXISTS ld_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL REFERENCES auth.users(id),
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  pregnancy_id uuid NOT NULL REFERENCES ld_pregnancies(id),
  alert_type text NOT NULL,
  severity text NOT NULL CHECK (severity IN ('critical','high','medium','low')),
  message text NOT NULL,
  source_record_id uuid,
  acknowledged boolean NOT NULL DEFAULT false,
  acknowledged_by uuid,
  acknowledged_at timestamptz,
  resolved boolean NOT NULL DEFAULT false,
  resolved_by uuid,
  resolved_at timestamptz,
  resolution_notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_ld_alerts_patient ON ld_alerts(patient_id);
CREATE INDEX idx_ld_alerts_pregnancy ON ld_alerts(pregnancy_id);
CREATE INDEX idx_ld_alerts_tenant ON ld_alerts(tenant_id);
CREATE INDEX idx_ld_alerts_active ON ld_alerts(tenant_id, resolved) WHERE resolved = false;
CREATE INDEX idx_ld_alerts_severity ON ld_alerts(severity);

-- RLS
ALTER TABLE ld_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY ld_alerts_tenant_read ON ld_alerts FOR SELECT
  USING (tenant_id IN (SELECT id FROM tenants WHERE id = (SELECT (current_setting('app.current_tenant_id', true))::uuid)));

CREATE POLICY ld_alerts_service_insert ON ld_alerts FOR INSERT WITH CHECK (true);

CREATE POLICY ld_alerts_service_update ON ld_alerts FOR UPDATE USING (true) WITH CHECK (true);
