-- ============================================================================
-- RPM FEE SCHEDULE RATES + ENCOUNTER TYPE DOCUMENTATION
-- ============================================================================
-- Seeds default CMS national average rates for RPM CPT codes into the
-- fee_schedule_rates table so rpmClaimService can generate priced claims.
--
-- Source: G-11 system gap (docs/trackers/system-gaps-tracker.md)
-- CPT rates: 2026 CMS Physician Fee Schedule (national average, non-facility)
-- ============================================================================

-- ============================================================================
-- 1. CREATE DEFAULT RPM FEE SCHEDULE
-- ============================================================================

INSERT INTO public.fee_schedules (name, payer_type, effective_date, is_active, notes)
VALUES (
  'RPM Default — CMS 2026',
  'medicare',
  '2026-01-01',
  true,
  'Default RPM CPT rates based on 2026 CMS Physician Fee Schedule national averages. Override per-payer via additional fee_schedule entries.'
)
ON CONFLICT (payer_type, effective_date, locality) DO NOTHING;

-- ============================================================================
-- 2. SEED RPM CPT FEE SCHEDULE RATES
-- ============================================================================
-- Uses a CTE to get the fee schedule ID we just inserted (or that already exists)

WITH rpm_schedule AS (
  SELECT id FROM public.fee_schedules
  WHERE name = 'RPM Default — CMS 2026'
  AND payer_type = 'medicare'
  AND effective_date = '2026-01-01'
  LIMIT 1
)
INSERT INTO public.fee_schedule_rates (fee_schedule_id, code_type, code, description, rate, time_required_minutes, notes)
SELECT
  rpm_schedule.id,
  vals.code_type,
  vals.code,
  vals.description,
  vals.rate,
  vals.time_minutes,
  vals.notes
FROM rpm_schedule,
(VALUES
  ('cpt', '99453', 'RPM device setup and patient education (one-time)', 19.46, 0, 'Billed once per enrollment at initial device setup'),
  ('cpt', '99454', 'RPM device supply with daily recordings (≥16 days/30-day period)', 62.44, 0, 'Requires ≥16 transmission days per 30-day billing period'),
  ('cpt', '99457', 'RPM treatment management, first 20 minutes', 50.94, 20, 'Requires ≥20 cumulative minutes of clinical monitoring'),
  ('cpt', '99458', 'RPM treatment management, each additional 20 minutes', 41.17, 20, 'Each additional 20-min block beyond CPT 99457')
) AS vals(code_type, code, description, rate, time_minutes, notes)
ON CONFLICT (fee_schedule_id, code_type, code) DO UPDATE SET
  rate = EXCLUDED.rate,
  description = EXCLUDED.description,
  notes = EXCLUDED.notes;

-- ============================================================================
-- 3. DOCUMENT RPM ENCOUNTER TYPE
-- ============================================================================

COMMENT ON COLUMN public.encounters.encounter_type IS
  'Encounter classification: inpatient, outpatient, telehealth, emergency, rpm (Remote Patient Monitoring). RPM encounters are auto-generated by rpmClaimService for billing CPT 99453-99458.';
