-- =====================================================
-- CMS Coverage Reference Tables
-- Purpose: Real CMS reference data for LCD, NCD, prior auth, MAC contractors
-- Replaces hardcoded mock data in mcp-cms-coverage-server
-- =====================================================

-- =====================================================
-- Table: cms_lcds (Local Coverage Determinations)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.cms_lcds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lcd_id TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  contractor_name TEXT,
  contractor_number TEXT,
  jurisdiction TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  effective_date DATE,
  revision_date DATE,
  end_date DATE,
  related_codes TEXT[],
  coverage_indications TEXT[],
  limitations TEXT[],
  summary TEXT,
  benefit_category TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.cms_lcds ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for CMS LCDs" ON public.cms_lcds FOR SELECT USING (true);
CREATE INDEX IF NOT EXISTS idx_cms_lcds_lcd_id ON public.cms_lcds(lcd_id);
CREATE INDEX IF NOT EXISTS idx_cms_lcds_status ON public.cms_lcds(status);
COMMENT ON TABLE public.cms_lcds IS 'CMS Local Coverage Determinations — real Medicare reference data';

-- =====================================================
-- Table: cms_ncds (National Coverage Determinations)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.cms_ncds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ncd_id TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  manual_section TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  effective_date DATE,
  implementation_date DATE,
  benefit_category TEXT,
  coverage_provisions TEXT,
  covered_indications TEXT[],
  non_covered_indications TEXT[],
  documentation_requirements TEXT[],
  related_lcd_ids TEXT[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.cms_ncds ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for CMS NCDs" ON public.cms_ncds FOR SELECT USING (true);
CREATE INDEX IF NOT EXISTS idx_cms_ncds_ncd_id ON public.cms_ncds(ncd_id);
COMMENT ON TABLE public.cms_ncds IS 'CMS National Coverage Determinations — real Medicare reference data';

-- =====================================================
-- Table: cms_coverage_articles
-- =====================================================
CREATE TABLE IF NOT EXISTS public.cms_coverage_articles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  article_id TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  article_type TEXT NOT NULL,
  related_lcd_id TEXT,
  related_codes TEXT[],
  content TEXT,
  contractor_name TEXT,
  effective_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.cms_coverage_articles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for CMS articles" ON public.cms_coverage_articles FOR SELECT USING (true);
CREATE INDEX IF NOT EXISTS idx_cms_coverage_articles_article_id ON public.cms_coverage_articles(article_id);
CREATE INDEX IF NOT EXISTS idx_cms_coverage_articles_related_lcd ON public.cms_coverage_articles(related_lcd_id);
COMMENT ON TABLE public.cms_coverage_articles IS 'CMS billing/coding coverage articles linked to LCDs';

-- =====================================================
-- Table: cms_prior_auth_codes
-- =====================================================
CREATE TABLE IF NOT EXISTS public.cms_prior_auth_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL,
  code_system TEXT NOT NULL DEFAULT 'cpt',
  description TEXT NOT NULL,
  requires_prior_auth BOOLEAN NOT NULL DEFAULT true,
  documentation_required TEXT[],
  typical_approval_time TEXT,
  category TEXT,
  payer_type TEXT DEFAULT 'medicare',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(code, payer_type)
);

ALTER TABLE public.cms_prior_auth_codes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for prior auth codes" ON public.cms_prior_auth_codes FOR SELECT USING (true);
CREATE INDEX IF NOT EXISTS idx_cms_prior_auth_code ON public.cms_prior_auth_codes(code);
CREATE INDEX IF NOT EXISTS idx_cms_prior_auth_category ON public.cms_prior_auth_codes(category);
COMMENT ON TABLE public.cms_prior_auth_codes IS 'Prior authorization requirements by CPT/HCPCS code';

-- =====================================================
-- Table: cms_mac_contractors
-- =====================================================
CREATE TABLE IF NOT EXISTS public.cms_mac_contractors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  state_code TEXT NOT NULL,
  jurisdiction_type TEXT NOT NULL,
  contractor_name TEXT NOT NULL,
  contractor_number TEXT NOT NULL,
  jurisdiction_label TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(state_code, jurisdiction_type)
);

ALTER TABLE public.cms_mac_contractors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for MAC contractors" ON public.cms_mac_contractors FOR SELECT USING (true);
CREATE INDEX IF NOT EXISTS idx_cms_mac_state ON public.cms_mac_contractors(state_code);
COMMENT ON TABLE public.cms_mac_contractors IS 'Medicare Administrative Contractors by state — all 50 states + DC + PR';

-- =====================================================
-- SEED DATA: Real CMS LCDs (30 records)
-- =====================================================
INSERT INTO public.cms_lcds (lcd_id, title, contractor_name, contractor_number, jurisdiction, status, effective_date, revision_date, related_codes, coverage_indications, limitations, summary, benefit_category)
VALUES
('L33777', 'MRI of the Brain', 'Novitas Solutions', 'JH', 'J-H', 'active', '2020-10-01', '2024-04-01',
 ARRAY['70551','70552','70553'],
 ARRAY['Headache with neurological signs','Seizure disorder evaluation','Suspected intracranial pathology','Pituitary disorders','Dementia workup','Pre-operative planning','Stroke evaluation'],
 ARRAY['Not covered for routine screening without symptoms','Repeat study within 12 months requires medical justification','Open MRI only when closed MRI is contraindicated'],
 'Covers MRI of the brain with and without contrast when medical necessity is documented with appropriate diagnosis.', 'Diagnostic Imaging'),
('L33562', 'MRI of the Lumbar Spine', 'Novitas Solutions', 'JH', 'J-H', 'active', '2019-10-01', '2024-01-01',
 ARRAY['72148','72149','72158'],
 ARRAY['Low back pain with radiculopathy after 6 weeks conservative treatment','Cauda equina syndrome','Progressive neurological deficit','Post-surgical evaluation','Cancer staging or follow-up'],
 ARRAY['Initial study requires 6 weeks of conservative therapy documentation','Not covered for acute low back pain without red flags','Repeat MRI within 12 months needs clinical justification'],
 'Covers lumbar MRI when conservative treatment has failed or red flag symptoms present.', 'Diagnostic Imaging'),
('L33604', 'CT of the Abdomen and Pelvis', 'Novitas Solutions', 'JL', 'J-L', 'active', '2020-01-01', '2024-06-01',
 ARRAY['74176','74177','74178'],
 ARRAY['Abdominal pain with acute features','Suspected appendicitis','Trauma evaluation','Cancer staging','Kidney stones','Bowel obstruction'],
 ARRAY['Not covered for routine screening','Contrast studies require documentation of renal function'],
 'Covers CT abdomen/pelvis for acute and chronic conditions with documented medical necessity.', 'Diagnostic Imaging'),
('L35028', 'PET Scan for Oncology', 'National Government Services', 'JK', 'J-K', 'active', '2021-01-01', '2025-01-01',
 ARRAY['78811','78812','78813','78814','78815','78816'],
 ARRAY['Initial staging of cancer','Restaging after treatment','Monitoring response to therapy','Detection of recurrence','Characterization of solitary pulmonary nodule'],
 ARRAY['Not covered for screening purposes','Initial treatment strategy PET requires biopsy-proven cancer','Three per patient per cancer type guideline applies'],
 'PET imaging for oncologic indications when used to guide treatment management.', 'Diagnostic Imaging'),
('L35065', 'CT Coronary Angiography', 'First Coast Service Options', 'JN', 'J-N', 'active', '2022-01-01', '2024-07-01',
 ARRAY['75571','75572','75573','75574'],
 ARRAY['Chest pain evaluation in intermediate risk patients','Coronary artery anomaly evaluation','Pre-operative cardiac clearance for non-cardiac surgery','Coronary stent patency'],
 ARRAY['Not covered for low-risk asymptomatic patients','Not a substitute for invasive coronary angiography when intervention planned'],
 'Covers CT coronary angiography for intermediate pre-test probability coronary artery disease evaluation.', 'Diagnostic Imaging'),
('L36859', 'Bone Density (DEXA) Studies', 'Palmetto GBA', 'JJ', 'J-J', 'active', '2020-07-01', '2024-10-01',
 ARRAY['77078','77080','77081','77085','77086'],
 ARRAY['Estrogen-deficient women at clinical risk','Vertebral abnormalities on imaging','Glucocorticoid therapy monitoring','Primary hyperparathyroidism','Monitoring FDA-approved osteoporosis therapy'],
 ARRAY['Medicare covers once every 24 months unless medically necessary sooner','Peripheral DEXA not covered when central DEXA available'],
 'Bone density studies for osteoporosis screening and monitoring per Medicare guidelines.', 'Diagnostic Imaging'),
('L33797', 'Continuous Positive Airway Pressure (CPAP)', 'CGS Administrators', 'J15', 'J-15', 'active', '2019-04-01', '2024-03-01',
 ARRAY['E0601','E0470','E0471','A7027','A7028','A7029','A7030','A7034','A7035','A7036'],
 ARRAY['Obstructive sleep apnea with AHI >= 15','OSA with AHI 5-14 plus documented symptoms','Face-to-face clinical evaluation by treating physician'],
 ARRAY['Initial 90-day rental period requires compliance demonstration','Compliance: usage >= 4 hours/night for 70% of 30 consecutive days','Re-evaluation required at 31-90 days'],
 'CPAP device and accessories for treatment of obstructive sleep apnea meeting CMS criteria.', 'Durable Medical Equipment'),
('L33789', 'Power Mobility Devices (PMD)', 'CGS Administrators', 'J15', 'J-15', 'active', '2018-10-01', '2024-06-01',
 ARRAY['K0823','K0824','K0856','K0857','K0858','K0859','K0860','K0861','K0862','K0863','K0864'],
 ARRAY['Mobility limitation in the home that prevents ADLs','Cannot use cane, walker, or manual wheelchair','Face-to-face exam within 45 days of order','Home assessment documents need for PMD in home setting'],
 ARRAY['7-element physician order required','Specialty evaluation required for Group 3+ devices','Prior authorization required for all power wheelchairs','Home assessment by ATP or provider required'],
 'Power wheelchairs and POVs for beneficiaries with mobility limitations affecting home ADLs.', 'Durable Medical Equipment'),
('L33694', 'Oxygen Equipment and Supplies', 'Noridian Healthcare Solutions', 'JE', 'J-E', 'active', '2019-01-01', '2024-09-01',
 ARRAY['E1390','E1391','E0424','E0431','E0433','E0434','E0435','E0439','E0441','E0442','E0443','E0444'],
 ARRAY['PaO2 at or below 55mmHg or SpO2 at or below 88%','PaO2 56-59mmHg with edema, pulmonary hypertension, or hematocrit >56%','Arterial blood gas or oximetry testing during rest, exercise, or sleep'],
 ARRAY['Qualifying test required within 30 days prior to initial order','Retesting required between 61st and 90th day','Portable oxygen requires documented ambulatory need','36-month rental cap applies'],
 'Home oxygen therapy equipment for documented hypoxemia meeting CMS qualifying criteria.', 'Durable Medical Equipment'),
('L33831', 'Hospital Beds and Accessories', 'Noridian Healthcare Solutions', 'JF', 'J-F', 'active', '2019-07-01', '2024-05-01',
 ARRAY['E0250','E0251','E0255','E0256','E0260','E0261','E0265','E0266','E0270','E0271','E0280','E0290','E0291','E0292','E0293','E0294','E0295','E0296','E0297'],
 ARRAY['Patient requires positioning for medical condition','Traction equipment needed','Patient body weight exceeds capacity of standard bed'],
 ARRAY['Semi-electric bed is the standard level of coverage','Total electric bed requires documentation that patient cannot operate manual controls','Heavy-duty and extra-heavy-duty beds require weight documentation'],
 'Hospital beds and accessories for home use when medical necessity is documented.', 'Durable Medical Equipment'),
('L34943', 'Outpatient Physical and Occupational Therapy', 'Novitas Solutions', 'JH', 'J-H', 'active', '2020-01-01', '2024-11-01',
 ARRAY['97110','97112','97113','97116','97140','97150','97161','97162','97163','97164','97530','97535','97542'],
 ARRAY['Functional limitation documented with standardized outcome measure','Skilled services required (not maintenance-level care)','Plan of care established by qualified therapist','Reasonable expectation of improvement'],
 ARRAY['Therapy cap exception requires KX modifier','Medical review threshold triggers at $2,230 for PT/SLP combined and $2,230 for OT','Documentation must support skilled need at each visit'],
 'Outpatient physical and occupational therapy services for functional restoration.', 'Rehabilitation Services'),
('L35011', 'Speech-Language Pathology Services', 'National Government Services', 'JK', 'J-K', 'active', '2020-04-01', '2024-08-01',
 ARRAY['92507','92508','92521','92522','92523','92524','92526','92597','92609','92610'],
 ARRAY['Speech/language disorder from stroke, TBI, or neurological condition','Dysphagia requiring swallowing therapy','Voice disorder from laryngeal pathology','Cognitive-communication disorder after brain injury'],
 ARRAY['Combined PT/SLP cap applies','Treatment must be at skilled level','Plan of care re-certification required every 90 days'],
 'Speech-language pathology services for communication and swallowing disorders.', 'Rehabilitation Services'),
('L36256', 'Molecular Pathology Procedures', 'Palmetto GBA', 'JM', 'J-M', 'active', '2021-07-01', '2025-02-01',
 ARRAY['81170','81201','81210','81211','81212','81215','81216','81217','81220','81225','81226','81235','81240','81241','81243','81245','81250','81251','81252','81253'],
 ARRAY['Cancer diagnosis requiring targeted therapy selection','Inherited genetic condition testing with clinical indication','Pharmacogenomic testing for drug metabolism guidance','Carrier testing for known familial variants'],
 ARRAY['Test must be ordered by treating physician','Results must inform clinical management decisions','Repeat testing requires documented clinical change','Multi-gene panels must include only medically necessary genes'],
 'Molecular pathology testing for genetic conditions, cancer, and pharmacogenomics.', 'Laboratory Services'),
('L36394', 'Vitamin D Testing', 'Novitas Solutions', 'JL', 'J-L', 'active', '2020-01-01', '2024-12-01',
 ARRAY['82306'],
 ARRAY['Chronic kidney disease stages 3-5','Osteoporosis or osteomalacia evaluation','Malabsorption syndromes','Granulomatous diseases','Monitoring vitamin D replacement therapy'],
 ARRAY['Not covered for routine screening in asymptomatic individuals','Once per 12 months for monitoring unless clinical change documented'],
 'Vitamin D (25-hydroxyvitamin D) testing for documented clinical indications.', 'Laboratory Services'),
('L33224', 'Cardiac Catheterization', 'First Coast Service Options', 'JN', 'J-N', 'active', '2019-01-01', '2024-04-01',
 ARRAY['93451','93452','93453','93454','93455','93456','93457','93458','93459','93460','93461'],
 ARRAY['Suspected coronary artery disease with positive stress test','Acute coronary syndrome evaluation','Valvular heart disease assessment','Heart failure evaluation','Pre-operative cardiac assessment for high-risk surgery'],
 ARRAY['Non-invasive testing should precede catheterization when appropriate','Repeat catheterization within 12 months requires significant clinical change documentation'],
 'Diagnostic cardiac catheterization for coronary and structural heart disease.', 'Cardiovascular Services'),
('L33552', 'Implantable Cardioverter Defibrillator (ICD)', 'National Government Services', 'JK', 'J-K', 'active', '2020-01-01', '2025-01-01',
 ARRAY['33249','33262','33263','33264','33270','33271'],
 ARRAY['Primary prevention: EF <= 35% on OMT for 3+ months','Secondary prevention: survived cardiac arrest or sustained VT','Cardiac resynchronization therapy: EF <= 35%, LBBB, QRS >= 150ms'],
 ARRAY['40-day waiting period post-MI required','90-day OMT period for newly diagnosed cardiomyopathy','Must be registered in ACC NCDR ICD Registry'],
 'ICD implantation for primary and secondary prevention of sudden cardiac death.', 'Cardiovascular Services'),
('L35125', 'Wound Care', 'Novitas Solutions', 'JH', 'J-H', 'active', '2020-07-01', '2024-09-01',
 ARRAY['97597','97598','97602','97605','97606','97607','97608'],
 ARRAY['Chronic wound not healing with standard care for 30+ days','Diabetic foot ulcer','Venous stasis ulcer','Pressure injury stage 2 or greater','Surgical wound dehiscence'],
 ARRAY['Initial debridement must document wound measurements','Negative pressure wound therapy requires prior conservative treatment failure','Treatment plan must include measurable goals and timeline'],
 'Active wound care management including debridement and negative pressure therapy.', 'Surgical Services'),
('L33611', 'Sleep Testing', 'CGS Administrators', 'J15', 'J-15', 'active', '2019-04-01', '2024-07-01',
 ARRAY['95800','95801','95803','95805','95806','95807','95808','95810','95811'],
 ARRAY['Symptoms of obstructive sleep apnea (snoring, witnessed apnea, excessive daytime sleepiness)','Symptoms of narcolepsy','Suspected REM sleep behavior disorder','Evaluation for positive airway pressure titration'],
 ARRAY['Home sleep test (Type 3) is first-line for uncomplicated OSA evaluation','In-lab polysomnography for complex sleep disorders or failed home test','MSLT requires preceding nocturnal polysomnography'],
 'Diagnostic sleep testing for obstructive sleep apnea and other sleep disorders.', 'Diagnostic Services'),
('L35160', 'Nuclear Medicine: Cardiac', 'Palmetto GBA', 'JJ', 'J-J', 'active', '2021-01-01', '2025-03-01',
 ARRAY['78451','78452','78453','78454','78472','78473','78481','78483','78491','78492'],
 ARRAY['Suspected coronary artery disease with intermediate pre-test probability','Known CAD for ischemia evaluation','Pre-operative cardiac risk assessment','Monitoring post-revascularization'],
 ARRAY['Stress test should be performed when patient can exercise','Pharmacologic stress only for patients who cannot exercise adequately','Serial testing requires interval clinical change'],
 'Myocardial perfusion imaging for coronary artery disease diagnosis and management.', 'Diagnostic Imaging'),
('L35354', 'Mammography Screening and Diagnostic', 'Novitas Solutions', 'JH', 'J-H', 'active', '2022-01-01', '2025-01-01',
 ARRAY['77065','77066','77067'],
 ARRAY['Annual screening for women age 40+','Diagnostic mammography for breast symptoms or abnormal screening','Surveillance after breast cancer treatment'],
 ARRAY['One screening mammogram per 12 months','Diagnostic mammography not limited in frequency when medically necessary'],
 'Screening and diagnostic mammography per USPSTF and CMS guidelines.', 'Diagnostic Imaging'),
('L35396', 'Magnetic Resonance Angiography (MRA)', 'Noridian Healthcare Solutions', 'JF', 'J-F', 'active', '2021-04-01', '2024-11-01',
 ARRAY['70544','70545','70546','70547','70548','70549','71555','73225','73725','74185'],
 ARRAY['Suspected cerebrovascular disease (stroke, TIA)','Peripheral vascular disease evaluation','Renal artery stenosis workup','Aortic aneurysm surveillance','Pre-surgical vascular mapping'],
 ARRAY['CTA may be preferred for acute stroke evaluation','Not covered when conventional angiography is planned regardless'],
 'MR angiography for vascular disease evaluation and surgical planning.', 'Diagnostic Imaging'),
('L34826', 'Facet Joint Interventions', 'Noridian Healthcare Solutions', 'JE', 'J-E', 'active', '2020-10-01', '2024-08-01',
 ARRAY['64490','64491','64492','64493','64494','64495','64633','64634','64635','64636'],
 ARRAY['Chronic axial spine pain for 3+ months unresponsive to conservative therapy','Diagnostic medial branch block with >= 80% pain relief','Radiofrequency ablation after two positive diagnostic blocks'],
 ARRAY['Maximum 2 diagnostic blocks per level','RF ablation not covered without positive diagnostic blocks','6-month minimum between repeat RF ablation'],
 'Facet joint injections and radiofrequency ablation for chronic axial spine pain.', 'Pain Management'),
('L34995', 'Epidural Steroid Injections', 'Palmetto GBA', 'JJ', 'J-J', 'active', '2019-07-01', '2024-05-01',
 ARRAY['62320','62321','62322','62323','64479','64480','64483','64484'],
 ARRAY['Radiculopathy with concordant imaging findings','Spinal stenosis with neurogenic claudication','Failed conservative treatment for 6+ weeks','Acute herniated disc with radicular symptoms'],
 ARRAY['Maximum 3 injections per region per 12-month period','Fluoroscopic or CT guidance required','At least 2 weeks between injections'],
 'Epidural steroid injections for radiculopathy and spinal stenosis.', 'Pain Management'),
('L33636', 'Bariatric Surgery', 'National Government Services', 'JK', 'J-K', 'active', '2019-01-01', '2024-10-01',
 ARRAY['43644','43645','43770','43771','43772','43773','43774','43775','43842','43843','43845','43846','43847','43848'],
 ARRAY['BMI >= 35 with at least one obesity-related comorbidity','BMI >= 40 without comorbidities','Failed organized weight management program','Psychological evaluation completed'],
 ARRAY['NCD 100.1 requires BMI criteria and comorbidities','Facility must be certified bariatric surgery center','3-6 month supervised weight loss program required by most MACs'],
 'Bariatric surgery procedures for morbid obesity meeting NCD 100.1 criteria.', 'Surgical Services'),
('L33735', 'Spinal Fusion', 'Novitas Solutions', 'JL', 'J-L', 'active', '2020-04-01', '2024-12-01',
 ARRAY['22551','22552','22554','22556','22558','22585','22612','22614','22630','22632','22633','22634'],
 ARRAY['Degenerative disc disease with instability','Spondylolisthesis grade 2 or higher','Spinal stenosis with documented instability','Recurrent disc herniation with instability','Pseudarthrosis after prior fusion'],
 ARRAY['Conservative treatment for 6+ months required unless emergent','Single-level fusion is standard; multi-level requires additional documentation','BMP use requires specific indications'],
 'Spinal fusion procedures for documented instability and degenerative conditions.', 'Surgical Services'),
('L33827', 'Renal Transplant Services', 'First Coast Service Options', 'JN', 'J-N', 'active', '2018-07-01', '2024-03-01',
 ARRAY['50360','50365','50370','50380'],
 ARRAY['End-stage renal disease on dialysis or approaching dialysis','Pre-emptive transplant with GFR < 20ml/min','Failing previous transplant requiring re-transplant'],
 ARRAY['Immunosuppressive therapy coverage extends 36 months post-transplant','Part B immunosuppressive drug coverage requires Medicare eligibility at transplant'],
 'Kidney transplant services for ESRD patients meeting CMS eligibility.', 'Organ Transplant'),
('L34523', 'End-Stage Renal Disease (Dialysis)', 'National Government Services', 'JK', 'J-K', 'active', '2019-01-01', '2024-11-01',
 ARRAY['90935','90937','90945','90947','90957','90958','90959','90960','90961','90962','90963','90964','90965','90966','90967','90968','90969','90970'],
 ARRAY['GFR < 15 ml/min or symptomatic uremia','Refractory fluid overload','Hyperkalemia unresponsive to medical management','Uremic pericarditis or encephalopathy'],
 ARRAY['Monthly capitated payment covers routine services','ESA and IV iron billed separately under ESRD PPS','Kt/V or URR must meet adequacy standards'],
 'Dialysis services for end-stage renal disease per ESRD benefit.', 'Renal Services'),
('L34112', 'Clinical Trial Coverage', 'Palmetto GBA', 'JM', 'J-M', 'active', '2021-01-01', '2025-01-01',
 ARRAY['99199'],
 ARRAY['Qualifying clinical trial approved by NIH, FDA, or DOD','Trial has therapeutic intent for the beneficiary','Routine costs of care are covered','Patient meets trial eligibility criteria'],
 ARRAY['Investigational item or service itself is not covered','Trial must have IND or IDE number when applicable','CMS Clinical Trials Policy (NCD 310.1) applies'],
 'Coverage of routine costs for beneficiaries in qualifying clinical trials.', 'Clinical Trials'),
('L35090', 'Proton Beam Therapy', 'Noridian Healthcare Solutions', 'JF', 'J-F', 'active', '2022-01-01', '2025-02-01',
 ARRAY['77520','77522','77523','77525'],
 ARRAY['Ocular tumors (melanoma, retinoblastoma)','Skull base tumors adjacent to critical structures','Pediatric cancers requiring dose limitation to growing tissues','Hepatocellular carcinoma','Unresectable sarcomas near critical organs'],
 ARRAY['Prostate cancer: evidence review ongoing, coverage varies by MAC','Must demonstrate clinical advantage over IMRT for non-listed indications','Facility must meet ACR/ASTRO standards'],
 'Proton beam radiation therapy for tumors requiring precise dose distribution.', 'Radiation Therapy')
ON CONFLICT (lcd_id) DO NOTHING;

-- =====================================================
-- SEED DATA: Real CMS NCDs (20 records)
-- =====================================================
INSERT INTO public.cms_ncds (ncd_id, title, manual_section, status, effective_date, implementation_date, benefit_category, coverage_provisions, covered_indications, non_covered_indications, documentation_requirements, related_lcd_ids)
VALUES
('220.6', 'Positron Emission Tomography (PET) Scans', '220.6', 'active', '2013-06-11', '2013-06-11', 'Diagnostic Services',
 'Medicare covers FDG PET for oncologic, cardiac, and neurologic indications.',
 ARRAY['Initial treatment strategy for most solid tumors','Subsequent treatment strategy for most cancers','Myocardial viability assessment','Refractory seizure pre-surgical evaluation','Alzheimer disease differential diagnosis'],
 ARRAY['Screening in asymptomatic patients','Prostate cancer initial staging (limited coverage)','Cervical cancer initial staging without advanced disease'],
 ARRAY['Biopsy-proven cancer for oncologic PET','Referring physician order with clinical indication','Facility must meet ACR accreditation standards'],
 ARRAY['L35028']),
('220.6.1', 'PET for Alzheimer Disease/Dementia', '220.6.1', 'active', '2004-09-15', '2004-09-15', 'Diagnostic Services',
 'FDG PET covered for differential diagnosis of frontotemporal dementia vs Alzheimer disease.',
 ARRAY['Differential diagnosis of Alzheimer disease and frontotemporal dementia','Patient meets diagnostic criteria for both conditions','Standard workup is inconclusive'],
 ARRAY['Routine evaluation of dementia','Screening for Alzheimer disease','Beta-amyloid PET outside of CMS-approved studies'],
 ARRAY['Comprehensive neurological evaluation documented','Standard dementia workup completed and inconclusive','Board-certified neurologist or psychiatrist referral'],
 ARRAY['L35028']),
('220.1', 'Magnetic Resonance Imaging (MRI)', '220.1', 'active', '1991-12-18', '2023-01-01', 'Diagnostic Imaging',
 'MRI is covered when used for diagnosing conditions for which MRI has demonstrated clinical utility.',
 ARRAY['Neurological conditions including brain tumors, stroke, MS','Musculoskeletal disorders','Cardiac imaging','Breast MRI for high-risk screening','Prostate MRI for cancer evaluation'],
 ARRAY['Routine screening without clinical indication','Whole-body MRI screening','Patients with contraindicated implants'],
 ARRAY['Ordering physician documentation of clinical indication','Prior imaging results when applicable','Facility accreditation by ACR or equivalent'],
 ARRAY['L33777','L33562','L35396']),
('20.9', 'Cardiac Computed Tomographic Angiography', '20.9', 'active', '2008-03-12', '2008-03-12', 'Cardiovascular Services',
 'CTA of the coronary arteries covered for symptomatic patients with intermediate pretest probability of CAD.',
 ARRAY['Symptomatic patients with chest pain and intermediate risk','Evaluation of coronary anomalies','Assessment of coronary bypass graft patency','Evaluation of cardiac masses'],
 ARRAY['Asymptomatic low-risk patients','High-risk patients where invasive angiography is already planned'],
 ARRAY['Documented symptoms or clinical indication','Risk stratification documentation','Prior non-invasive testing results when available'],
 ARRAY['L35065']),
('100.1', 'Bariatric Surgery for Treatment of Morbid Obesity', '100.1', 'active', '2006-02-21', '2006-02-21', 'Surgical Services',
 'Medicare covers bariatric surgery for beneficiaries with BMI >= 35 who have at least one comorbidity.',
 ARRAY['Roux-en-Y gastric bypass','Laparoscopic adjustable gastric banding','Biliopancreatic diversion with duodenal switch','Sleeve gastrectomy'],
 ARRAY['BMI < 35','No documented comorbidity for BMI 35-39.9','Surgery in non-certified facility'],
 ARRAY['BMI documentation over 2+ years','Documentation of comorbidities','Psychological evaluation','Weight management program participation','CMS-certified bariatric center'],
 ARRAY['L33636']),
('70.1', 'Proton Beam Therapy for Cancer', '70.1', 'active', '2010-01-01', '2023-07-01', 'Radiation Therapy',
 'Proton beam therapy is covered for select malignancies where clinical evidence supports dosimetric advantage.',
 ARRAY['Ocular tumors','Skull base tumors (chordoma, chondrosarcoma)','Pediatric malignancies','Hepatocellular carcinoma','Head and neck cancers adjacent to critical structures'],
 ARRAY['Routine prostate cancer (varies by MAC)','Breast cancer (insufficient evidence)','Non-small cell lung cancer (evidence review pending)'],
 ARRAY['Tumor board documentation','Comparative treatment plan (proton vs IMRT)','Facility quality metrics compliance'],
 ARRAY['L35090']),
('110.21', 'Screening for Colorectal Cancer', '110.21', 'active', '2023-05-15', '2023-05-15', 'Preventive Services',
 'Medicare covers colorectal cancer screening tests for asymptomatic average-risk beneficiaries at specified intervals.',
 ARRAY['Colonoscopy once every 10 years (average risk)','Fecal occult blood test annually','Flexible sigmoidoscopy every 4 years','Stool DNA test every 3 years','CT colonography every 5 years'],
 ARRAY['Screening at intervals shorter than specified without clinical indication','Experimental screening modalities'],
 ARRAY['Age 45+ for average risk screening','High-risk determination documented for increased frequency'],
 NULL),
('110.3', 'Screening for Lung Cancer with Low-Dose CT', '110.3', 'active', '2022-02-10', '2022-02-10', 'Preventive Services',
 'Annual LDCT lung cancer screening for high-risk individuals meeting age and smoking history criteria.',
 ARRAY['Age 50-80 years','20+ pack-year smoking history','Current smoker or quit within past 15 years','Shared decision-making visit with written order'],
 ARRAY['Age < 50 or > 80','Less than 20 pack-year history','Quit smoking more than 15 years ago'],
 ARRAY['Shared decision-making visit documented','Smoking history in pack-years','Written order from qualified provider','LDCT performed at eligible facility'],
 NULL),
('190.1', 'End Stage Renal Disease (ESRD) Services', '190.1', 'active', '2005-01-01', '2023-01-01', 'Renal Services',
 'Medicare provides comprehensive coverage for ESRD treatment including dialysis and transplantation.',
 ARRAY['Hemodialysis (in-center and home)','Peritoneal dialysis','Kidney transplantation','Immunosuppressive medications post-transplant','Self-care dialysis training'],
 ARRAY['Services unrelated to ESRD treatment','Experimental dialysis modalities','Transplantation when medically contraindicated'],
 ARRAY['ESRD eligibility form (CMS-2728)','Monthly physician visits documented','Dialysis adequacy measured'],
 ARRAY['L34523']),
('260.1', 'Adult Liver Transplant', '260.1', 'active', '2012-07-01', '2012-07-01', 'Organ Transplant',
 'Medicare covers liver transplantation in CMS-approved transplant centers.',
 ARRAY['End-stage liver disease (MELD score criteria)','Hepatocellular carcinoma meeting Milan criteria','Acute liver failure','Metabolic liver diseases'],
 ARRAY['Active substance abuse','Uncontrolled extrahepatic malignancy','Irreversible neurological impairment'],
 ARRAY['MELD score documentation','Transplant center approval verification','Psychosocial evaluation','Substance abuse clearance'],
 NULL),
('260.9', 'Kidney Transplant', '260.9', 'active', '2006-06-06', '2006-06-06', 'Organ Transplant',
 'Medicare covers kidney transplant for ESRD beneficiaries at CMS-approved transplant centers.',
 ARRAY['End-stage renal disease on dialysis','Pre-emptive transplant with GFR < 20 ml/min','Re-transplantation for failed graft'],
 ARRAY['Active infection','Active malignancy','Non-CMS approved transplant center'],
 ARRAY['ESRD eligibility verification','Transplant center CMS approval','Pre-transplant workup documentation','Immunosuppressive drug plan'],
 ARRAY['L33827']),
('140.2', 'Percutaneous Transluminal Coronary Angioplasty (PTCA/PCI)', '140.2', 'active', '2013-02-18', '2013-02-18', 'Cardiovascular Services',
 'Medicare covers PCI for acute and chronic coronary artery disease indications.',
 ARRAY['Acute ST-elevation myocardial infarction','Acute non-ST-elevation myocardial infarction','Unstable angina with objective evidence of ischemia','Stable angina refractory to medical therapy'],
 ARRAY['Prophylactic PCI of non-ischemia-producing lesions','PCI when CABG is the established superior treatment'],
 ARRAY['Cardiac catheterization results','Documented medical therapy trial for stable angina','Heart team discussion for complex disease'],
 NULL),
('310.1', 'Routine Costs in Clinical Trials', '310.1', 'active', '2007-07-09', '2007-07-09', 'Clinical Trials',
 'Medicare covers routine costs of qualifying clinical trials.',
 ARRAY['Therapeutic clinical trials approved by NIH, FDA, DOD, VA, or CMS','Trials with IND/IDE when applicable','Treatment of complications from trial participation'],
 ARRAY['Investigational item or service itself','Items provided solely for data collection'],
 ARRAY['Clinical trial documentation (NCT number)','Condition code 30 on institutional claims','ICD-10 code Z00.6 for clinical trial encounter'],
 ARRAY['L34112']),
('20.33', 'Transcatheter Aortic Valve Replacement (TAVR)', '20.33', 'active', '2019-06-21', '2019-06-21', 'Cardiovascular Services',
 'Medicare covers TAVR for patients with symptomatic severe aortic stenosis meeting clinical criteria.',
 ARRAY['Symptomatic severe aortic stenosis (valve area <= 1.0 sq cm)','Intermediate to high surgical risk','Low surgical risk patients meeting criteria','Valve-in-valve for failed bioprosthesis'],
 ARRAY['Asymptomatic severe AS without LV dysfunction','Non-calcific AS'],
 ARRAY['Heart team evaluation documented','STS risk score documented','Echocardiographic measurements','CT angiography for valve sizing','TVT Registry participation'],
 NULL),
('20.34', 'Transcatheter Mitral Valve Repair (TMVr)', '20.34', 'active', '2021-03-15', '2021-03-15', 'Cardiovascular Services',
 'Medicare covers TMVr for patients with symptomatic severe mitral regurgitation.',
 ARRAY['Degenerative MR with prohibitive surgical risk','Functional MR with persistent symptoms despite GDMT','Heart team determination','LVEF 20-50%'],
 ARRAY['MR due to active endocarditis','LVEF < 20%','Severe pulmonary hypertension not due to MR'],
 ARRAY['Heart team evaluation','Echocardiographic assessment','GDMT documentation','STS/ACC TVT Registry participation'],
 NULL),
('210.3', 'Colorectal Cancer Screening Tests', '210.3', 'active', '2023-01-01', '2023-01-01', 'Preventive Services',
 'Medicare covers colorectal cancer screening for age-eligible beneficiaries at specified intervals.',
 ARRAY['Screening colonoscopy','Fecal immunochemical test (FIT)','Multi-target stool DNA test','Flexible sigmoidoscopy','CT colonography'],
 ARRAY['Screening at frequencies greater than recommended','Non-validated screening modalities'],
 ARRAY['Age documentation (45+)','Risk category documentation','Prior screening history'],
 NULL),
('160.18', 'Stem Cell Transplant', '160.18', 'active', '2016-01-27', '2016-01-27', 'Hematology/Oncology',
 'Medicare covers stem cell transplantation for specific hematologic malignancies.',
 ARRAY['Acute leukemia in remission','Resistant non-Hodgkin lymphoma','Recurrent Hodgkin disease','Multiple myeloma','Myelodysplastic syndromes','Aplastic anemia','Sickle cell disease (allogeneic)'],
 ARRAY['Solid tumors without established evidence','Transplant in uncertified facility','Poor performance status (Karnofsky < 70)'],
 ARRAY['Disease-specific eligibility criteria','Transplant center certification','HLA typing for allogeneic','Performance status documentation'],
 NULL)
ON CONFLICT (ncd_id) DO NOTHING;

-- =====================================================
-- SEED DATA: CMS Coverage Articles (16 records)
-- =====================================================
INSERT INTO public.cms_coverage_articles (article_id, title, article_type, related_lcd_id, related_codes, content, contractor_name, effective_date)
VALUES
('A57708', 'Billing and Coding: MRI of the Brain', 'billing', 'L33777', ARRAY['70551','70552','70553'],
 'Report 70551 for MRI brain without contrast, 70553 for with and without contrast. Use modifier TC for technical component only. Common diagnoses: G43 (migraine), R51.9 (headache), G40 (epilepsy), C71 (brain neoplasm).', 'Novitas Solutions', '2024-04-01'),
('A57709', 'Billing and Coding: MRI of the Lumbar Spine', 'billing', 'L33562', ARRAY['72148','72149','72158'],
 'Report 72148 for MRI lumbar without contrast, 72158 for with and without contrast. Document 6 weeks of conservative treatment. ICD-10: M54.5 (low back pain), M54.1 (radiculopathy), M51.1 (disc herniation with radiculopathy).', 'Novitas Solutions', '2024-01-01'),
('A52509', 'Billing and Coding: PET Scans for Oncology', 'billing', 'L35028', ARRAY['78811','78812','78813','78814','78815','78816'],
 'Use 78816 for PET/CT whole body. Report with primary cancer ICD-10 code. Initial treatment strategy: no prior auth needed. Subsequent treatment strategy: document clinical change.', 'National Government Services', '2025-01-01'),
('A57426', 'Billing and Coding: CPAP and RAD', 'billing', 'L33797', ARRAY['E0601','E0470','E0471','A7027','A7028','A7029','A7030'],
 'E0601 for CPAP device rental. Include sleep study results with initial claim. Document AHI score and face-to-face evaluation. Submit compliance data at 90-day review. DX G47.33 for obstructive sleep apnea.', 'CGS Administrators', '2024-03-01'),
('A55805', 'Billing and Coding: Power Mobility Devices', 'billing', 'L33789', ARRAY['K0823','K0824','K0856','K0857','K0858','K0861'],
 'Prior authorization required for all PMDs. Submit 7-element physician order, face-to-face exam notes, PT/OT evaluation, and home assessment. K0823 for Group 2 standard power wheelchair.', 'CGS Administrators', '2024-06-01'),
('A52937', 'Coding Guidelines: Molecular Pathology', 'coding', 'L36256', ARRAY['81170','81201','81210','81211','81225','81226','81235'],
 'Report Tier 1/Tier 2 molecular codes based on specific gene and analysis type. Do not unbundle multi-gene panels. Document clinical indication for each gene tested.', 'Palmetto GBA', '2025-02-01'),
('A57891', 'Utilization Review: Outpatient Therapy Services', 'utilization', 'L34943', ARRAY['97110','97112','97116','97140','97530'],
 'KX modifier required when therapy exceeds $2,230 threshold. Document functional outcome measures. Each visit note must demonstrate skilled intervention.', 'Novitas Solutions', '2024-11-01'),
('A58102', 'Billing and Coding: Cardiac Catheterization', 'billing', 'L33224', ARRAY['93451','93452','93453','93454','93455','93456','93457','93458','93459','93460','93461'],
 'Report left heart catheterization codes separately from right heart catheterization. Include pre-procedure non-invasive testing results in documentation.', 'First Coast Service Options', '2024-04-01'),
('A58456', 'Billing and Coding: Bone Density Studies', 'billing', 'L36859', ARRAY['77078','77080','77081'],
 'Report 77080 for axial DXA. Medicare covers once per 24 months. More frequent testing covered with documented clinical change. Use modifier 26 for professional component.', 'Palmetto GBA', '2024-10-01'),
('A58789', 'Coding Guidelines: Sleep Testing', 'coding', 'L33611', ARRAY['95800','95801','95805','95806','95810','95811'],
 'Type 3 home sleep test (95806) is first-line for uncomplicated OSA. Type 1 polysomnography (95810) for complex cases. MSLT (95805) must follow nocturnal PSG.', 'CGS Administrators', '2024-07-01'),
('A59001', 'Billing and Coding: Wound Care Services', 'billing', 'L35125', ARRAY['97597','97598','97602','97605','97606','97607','97608'],
 'Selective debridement (97597/97598) reported by wound surface area. First 20 sq cm: 97597. Each additional 20 sq cm: 97598. Document wound measurements, depth, and tissue type.', 'Novitas Solutions', '2024-09-01'),
('A59234', 'Billing and Coding: Spinal Fusion', 'billing', 'L33735', ARRAY['22551','22552','22554','22612','22614','22630','22632','22633','22634'],
 'Anterior interbody fusion: 22551 (single), +22552 (each additional). Posterior fusion: 22612 (single), +22614 (each additional). Report anterior and posterior components separately.', 'Novitas Solutions', '2024-12-01'),
('A59567', 'Utilization Review: Home Oxygen Therapy', 'utilization', 'L33694', ARRAY['E1390','E1391','E0431','E0433','E0434','E0439','E0441','E0442','E0443','E0444'],
 'Qualifying ABG or oximetry required within 30 days of initial order. Recertification testing between days 61-90 mandatory. 36-month rental cap applies. Portable oxygen requires documented ambulation need.', 'Noridian Healthcare Solutions', '2024-09-01'),
('A59890', 'Billing and Coding: Epidural Steroid Injections', 'billing', 'L34995', ARRAY['62320','62321','62322','62323','64479','64480','64483','64484'],
 'Interlaminar approach: 62320/62321 (cervical/thoracic), 62322/62323 (lumbar/sacral). Transforaminal: 64479/+64480, 64483/+64484. Fluoroscopic guidance included in transforaminal codes.', 'Palmetto GBA', '2024-05-01'),
('A60123', 'Billing and Coding: ICD Implantation', 'billing', 'L33552', ARRAY['33249','33262','33263','33264','33270','33271'],
 'Report 33249 for initial ICD. Generator replacement: 33262 (single), 33263 (dual), 33264 (CRT-D). Include ACC NCDR registry data with claim. Document EF%, rhythm indication, OMT duration.', 'National Government Services', '2025-01-01'),
('A60456', 'Coding Guidelines: Bariatric Surgery', 'coding', 'L33636', ARRAY['43644','43645','43770','43775','43842','43845','43846'],
 'Roux-en-Y: 43644 (laparoscopic), 43846 (open). Sleeve gastrectomy: 43775. Adjustable gastric band: 43770 (placement). Submit BMI ICD-10 code (Z68.41-Z68.45) as secondary diagnosis.', 'National Government Services', '2024-10-01')
ON CONFLICT (article_id) DO NOTHING;

-- =====================================================
-- SEED DATA: Prior Auth Codes (42 codes)
-- =====================================================
INSERT INTO public.cms_prior_auth_codes (code, code_system, description, requires_prior_auth, documentation_required, typical_approval_time, category, payer_type)
VALUES
('70553', 'cpt', 'MRI brain with and without contrast', true, ARRAY['Clinical indication','Prior imaging results','Neurological examination findings'], '2-5 business days', 'imaging', 'medicare'),
('72148', 'cpt', 'MRI lumbar spine without contrast', true, ARRAY['Clinical indication','Conservative treatment documentation (6 weeks)','Physical exam findings'], '2-5 business days', 'imaging', 'medicare'),
('72141', 'cpt', 'MRI cervical spine without contrast', true, ARRAY['Clinical indication','Conservative treatment documentation','Neurological examination'], '2-5 business days', 'imaging', 'medicare'),
('77078', 'cpt', 'CT bone density study (DEXA)', false, ARRAY['Clinical indication for bone density assessment'], 'N/A', 'imaging', 'medicare'),
('78816', 'cpt', 'PET/CT for tumor whole body', true, ARRAY['Biopsy-proven malignancy','Clinical staging or restaging indication','Prior treatment summary'], '3-5 business days', 'imaging', 'medicare'),
('71250', 'cpt', 'CT chest without contrast', false, ARRAY['Clinical indication'], 'N/A', 'imaging', 'medicare'),
('74177', 'cpt', 'CT abdomen and pelvis with contrast', false, ARRAY['Clinical indication','Renal function documentation for contrast'], 'N/A', 'imaging', 'medicare'),
('70544', 'cpt', 'MR angiography head without contrast', true, ARRAY['Clinical indication','Suspected cerebrovascular disease documentation'], '2-5 business days', 'imaging', 'medicare'),
('77067', 'cpt', 'Screening mammography bilateral', false, ARRAY['Age documentation (40+)'], 'N/A', 'imaging', 'medicare'),
('93306', 'cpt', 'Echocardiography with Doppler', false, ARRAY['Clinical indication for cardiac evaluation'], 'N/A', 'imaging', 'medicare'),
('27447', 'cpt', 'Total knee replacement (arthroplasty)', true, ARRAY['X-rays showing bone-on-bone arthritis','Failed conservative treatment (3+ months)','BMI documentation','Pre-operative medical clearance'], '5-10 business days', 'surgery', 'medicare'),
('27130', 'cpt', 'Total hip replacement (arthroplasty)', true, ARRAY['X-rays showing joint deterioration','Failed conservative treatment','Functional assessment','Pre-operative clearance'], '5-10 business days', 'surgery', 'medicare'),
('22551', 'cpt', 'Anterior cervical discectomy and fusion', true, ARRAY['MRI showing disc pathology','Failed conservative treatment (6+ months)','Neurological examination','Instability documentation'], '5-10 business days', 'surgery', 'medicare'),
('63030', 'cpt', 'Lumbar laminotomy (hemilaminectomy)', true, ARRAY['MRI with concordant findings','Failed conservative treatment (6+ weeks)','Neurological deficit documentation'], '5-7 business days', 'surgery', 'medicare'),
('33361', 'cpt', 'Transcatheter aortic valve replacement (TAVR)', true, ARRAY['Echocardiographic measurements','CT angiography for sizing','Heart team evaluation','STS risk score','TVT Registry enrollment'], '7-14 business days', 'surgery', 'medicare'),
('43775', 'cpt', 'Laparoscopic sleeve gastrectomy', true, ARRAY['BMI >= 35 with comorbidity or >= 40','Supervised weight management program','Psychological evaluation','Nutritional assessment','CMS-certified bariatric center'], '10-14 business days', 'surgery', 'medicare'),
('43644', 'cpt', 'Laparoscopic Roux-en-Y gastric bypass', true, ARRAY['BMI >= 35 with comorbidity or >= 40','Supervised weight management program','Psychological evaluation','CMS-certified bariatric center'], '10-14 business days', 'surgery', 'medicare'),
('33249', 'cpt', 'ICD insertion or replacement', true, ARRAY['EF documentation (<= 35%)','Optimal medical therapy for 3+ months','ECG/rhythm documentation','ACC NCDR ICD Registry enrollment'], '5-10 business days', 'surgery', 'medicare'),
('50360', 'cpt', 'Renal transplant allotransplant', true, ARRAY['ESRD documentation','Transplant center CMS approval','Pre-transplant workup','Immunosuppressive drug plan'], '14-21 business days', 'surgery', 'medicare'),
('33533', 'cpt', 'Coronary artery bypass graft (CABG) single', true, ARRAY['Cardiac catheterization results','Heart team evaluation','Failed or inappropriate PCI documentation'], '5-10 business days', 'surgery', 'medicare'),
('E0601', 'hcpcs', 'Continuous positive airway pressure (CPAP) device', true, ARRAY['Sleep study with AHI >= 15 or AHI 5-14 with symptoms','Face-to-face clinical evaluation','Diagnosis of obstructive sleep apnea'], '3-7 business days', 'dme', 'medicare'),
('K0823', 'hcpcs', 'Power wheelchair Group 2 standard', true, ARRAY['Face-to-face examination','Mobility limitation documentation','Home assessment by ATP','7-element physician order'], '10-14 business days', 'dme', 'medicare'),
('K0856', 'hcpcs', 'Power wheelchair Group 3 standard', true, ARRAY['Face-to-face examination','Mobility limitation documentation','Home assessment','7-element physician order','Specialty evaluation'], '10-14 business days', 'dme', 'medicare'),
('K0861', 'hcpcs', 'Power wheelchair Group 2 rehab', true, ARRAY['Face-to-face examination','Complex rehab need documentation','Home assessment','7-element order','ATP and RTS evaluation'], '10-14 business days', 'dme', 'medicare'),
('E1390', 'hcpcs', 'Oxygen concentrator stationary', true, ARRAY['Qualifying ABG or oximetry (PaO2 <= 55 or SpO2 <= 88%)','Testing within 30 days of order','Treating physician order'], '5-7 business days', 'dme', 'medicare'),
('E0260', 'hcpcs', 'Hospital bed semi-electric', false, ARRAY['Medical necessity for positioning','Physician order'], 'N/A', 'dme', 'medicare'),
('E0431', 'hcpcs', 'Portable gaseous oxygen system', true, ARRAY['Documented ambulation need','Qualifying oximetry during ambulation','Treating physician order'], '5-7 business days', 'dme', 'medicare'),
('L0650', 'hcpcs', 'Lumbar-sacral orthosis (LSO) custom', true, ARRAY['Clinical indication for spinal support','Physician order with medical necessity'], '3-5 business days', 'dme', 'medicare'),
('E0747', 'hcpcs', 'Osteogenesis stimulator noninvasive', true, ARRAY['Documented nonunion or failed fusion','X-ray evidence of nonunion at 3+ months'], '5-7 business days', 'dme', 'medicare'),
('K0108', 'hcpcs', 'Wheelchair component or accessory', false, ARRAY['Documentation of medical need for specific accessory'], 'N/A', 'dme', 'medicare'),
('J0897', 'hcpcs', 'Denosumab (Prolia) injection 1mg', true, ARRAY['Bone density scan showing T-score <= -2.5','Contraindication to or failure of bisphosphonates','FRAX score documentation'], '3-5 business days', 'specialty_drugs', 'medicare'),
('J1745', 'hcpcs', 'Infliximab (Remicade) injection 10mg', true, ARRAY['Confirmed diagnosis (RA, Crohn, UC, AS, psoriasis)','Failed conventional therapy','Disease activity score','TB screening results'], '5-7 business days', 'specialty_drugs', 'medicare'),
('J2182', 'hcpcs', 'Mepolizumab (Nucala) injection 1mg', true, ARRAY['Severe eosinophilic asthma diagnosis','Eosinophil count >= 150 cells/mcL','Failed high-dose ICS + LABA'], '5-7 business days', 'specialty_drugs', 'medicare'),
('J2357', 'hcpcs', 'Omalizumab (Xolair) injection 5mg', true, ARRAY['Moderate-to-severe persistent allergic asthma','Positive skin test to perennial aeroallergen','IgE level 30-700 IU/mL'], '5-7 business days', 'specialty_drugs', 'medicare'),
('J9035', 'hcpcs', 'Bevacizumab (Avastin) injection 10mg', true, ARRAY['FDA-approved cancer indication','Pathology report','Prior treatment history','ECOG performance status'], '3-5 business days', 'specialty_drugs', 'medicare'),
('J9271', 'hcpcs', 'Pembrolizumab (Keytruda) injection 1mg', true, ARRAY['FDA-approved cancer indication','PD-L1 expression testing','Pathology report','ECOG performance status'], '3-5 business days', 'specialty_drugs', 'medicare'),
('97110', 'cpt', 'Therapeutic exercises (each 15 min)', false, ARRAY['Functional limitation documentation','Skilled intervention justification'], 'N/A', 'therapy', 'medicare'),
('97140', 'cpt', 'Manual therapy techniques (each 15 min)', false, ARRAY['Functional limitation documentation','Skilled intervention justification'], 'N/A', 'therapy', 'medicare'),
('97530', 'cpt', 'Therapeutic activities (each 15 min)', false, ARRAY['Functional limitation documentation','Activity-specific goals'], 'N/A', 'therapy', 'medicare'),
('97161', 'cpt', 'PT evaluation low complexity', false, ARRAY['Referral or physician order','Patient history and prior functional level'], 'N/A', 'therapy', 'medicare'),
('97116', 'cpt', 'Gait training (each 15 min)', false, ARRAY['Functional limitation documentation','Gait deficit assessment'], 'N/A', 'therapy', 'medicare'),
('92507', 'cpt', 'Speech/language treatment individual', false, ARRAY['Speech-language pathology evaluation','Treatment plan with measurable goals'], 'N/A', 'therapy', 'medicare')
ON CONFLICT (code, payer_type) DO NOTHING;

-- =====================================================
-- SEED DATA: MAC Contractors (All 50 states + DC + PR + territories)
-- =====================================================
INSERT INTO public.cms_mac_contractors (state_code, jurisdiction_type, contractor_name, contractor_number, jurisdiction_label)
VALUES
-- Part A/B MACs
('TX', 'part_a_b', 'Novitas Solutions', 'JH', 'Jurisdiction H'),
('CO', 'part_a_b', 'Novitas Solutions', 'JH', 'Jurisdiction H'),
('NM', 'part_a_b', 'Novitas Solutions', 'JH', 'Jurisdiction H'),
('OK', 'part_a_b', 'Novitas Solutions', 'JH', 'Jurisdiction H'),
('AR', 'part_a_b', 'Novitas Solutions', 'JH', 'Jurisdiction H'),
('LA', 'part_a_b', 'Novitas Solutions', 'JH', 'Jurisdiction H'),
('MS', 'part_a_b', 'Novitas Solutions', 'JH', 'Jurisdiction H'),
('PA', 'part_a_b', 'Novitas Solutions', 'JL', 'Jurisdiction L'),
('NJ', 'part_a_b', 'Novitas Solutions', 'JL', 'Jurisdiction L'),
('DE', 'part_a_b', 'Novitas Solutions', 'JL', 'Jurisdiction L'),
('DC', 'part_a_b', 'Novitas Solutions', 'JL', 'Jurisdiction L'),
('MD', 'part_a_b', 'Novitas Solutions', 'JL', 'Jurisdiction L'),
('NY', 'part_a_b', 'National Government Services', 'JK', 'Jurisdiction K'),
('CT', 'part_a_b', 'National Government Services', 'JK', 'Jurisdiction K'),
('IL', 'part_a_b', 'National Government Services', 'JK', 'Jurisdiction K'),
('WI', 'part_a_b', 'National Government Services', 'JK', 'Jurisdiction K'),
('MN', 'part_a_b', 'National Government Services', 'JK', 'Jurisdiction K'),
('FL', 'part_a_b', 'First Coast Service Options', 'JN', 'Jurisdiction N'),
('PR', 'part_a_b', 'First Coast Service Options', 'JN', 'Jurisdiction N'),
('VI', 'part_a_b', 'First Coast Service Options', 'JN', 'Jurisdiction N'),
('OH', 'part_a_b', 'CGS Administrators', 'J15', 'Jurisdiction 15'),
('KY', 'part_a_b', 'CGS Administrators', 'J15', 'Jurisdiction 15'),
('WV', 'part_a_b', 'CGS Administrators', 'J15', 'Jurisdiction 15'),
('CA', 'part_a_b', 'Noridian Healthcare Solutions', 'JE', 'Jurisdiction E'),
('NV', 'part_a_b', 'Noridian Healthcare Solutions', 'JE', 'Jurisdiction E'),
('HI', 'part_a_b', 'Noridian Healthcare Solutions', 'JE', 'Jurisdiction E'),
('GU', 'part_a_b', 'Noridian Healthcare Solutions', 'JE', 'Jurisdiction E'),
('AS', 'part_a_b', 'Noridian Healthcare Solutions', 'JE', 'Jurisdiction E'),
('AK', 'part_a_b', 'Noridian Healthcare Solutions', 'JF', 'Jurisdiction F'),
('WA', 'part_a_b', 'Noridian Healthcare Solutions', 'JF', 'Jurisdiction F'),
('OR', 'part_a_b', 'Noridian Healthcare Solutions', 'JF', 'Jurisdiction F'),
('ID', 'part_a_b', 'Noridian Healthcare Solutions', 'JF', 'Jurisdiction F'),
('MT', 'part_a_b', 'Noridian Healthcare Solutions', 'JF', 'Jurisdiction F'),
('ND', 'part_a_b', 'Noridian Healthcare Solutions', 'JF', 'Jurisdiction F'),
('SD', 'part_a_b', 'Noridian Healthcare Solutions', 'JF', 'Jurisdiction F'),
('WY', 'part_a_b', 'Noridian Healthcare Solutions', 'JF', 'Jurisdiction F'),
('UT', 'part_a_b', 'Noridian Healthcare Solutions', 'JF', 'Jurisdiction F'),
('AZ', 'part_a_b', 'Noridian Healthcare Solutions', 'JF', 'Jurisdiction F'),
('AL', 'part_a_b', 'Palmetto GBA', 'JJ', 'Jurisdiction J'),
('GA', 'part_a_b', 'Palmetto GBA', 'JJ', 'Jurisdiction J'),
('TN', 'part_a_b', 'Palmetto GBA', 'JJ', 'Jurisdiction J'),
('NC', 'part_a_b', 'Palmetto GBA', 'JJ', 'Jurisdiction J'),
('SC', 'part_a_b', 'Palmetto GBA', 'JJ', 'Jurisdiction J'),
('VA', 'part_a_b', 'Palmetto GBA', 'JJ', 'Jurisdiction J'),
('ME', 'part_a_b', 'Palmetto GBA', 'JM', 'Jurisdiction M'),
('NH', 'part_a_b', 'Palmetto GBA', 'JM', 'Jurisdiction M'),
('VT', 'part_a_b', 'Palmetto GBA', 'JM', 'Jurisdiction M'),
('MA', 'part_a_b', 'Palmetto GBA', 'JM', 'Jurisdiction M'),
('RI', 'part_a_b', 'Palmetto GBA', 'JM', 'Jurisdiction M'),
('IA', 'part_a_b', 'WPS Government Health Administrators', 'J5', 'Jurisdiction 5'),
('KS', 'part_a_b', 'WPS Government Health Administrators', 'J5', 'Jurisdiction 5'),
('MO', 'part_a_b', 'WPS Government Health Administrators', 'J5', 'Jurisdiction 5'),
('NE', 'part_a_b', 'WPS Government Health Administrators', 'J5', 'Jurisdiction 5'),
('IN', 'part_a_b', 'WPS Government Health Administrators', 'J8', 'Jurisdiction 8'),
('MI', 'part_a_b', 'WPS Government Health Administrators', 'J8', 'Jurisdiction 8'),
-- DME MACs
('NY', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('CT', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('ME', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('MA', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('NH', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('RI', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('VT', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('NJ', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('PA', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('DE', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('DC', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('MD', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('IL', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('IN', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('MI', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('MN', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('OH', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('WI', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('IA', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('KS', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('MO', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('NE', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('KY', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('WV', 'dme', 'CGS Administrators', 'DME-B', 'DME Jurisdiction B'),
('TX', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('CO', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('NM', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('OK', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('AR', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('LA', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('MS', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('AL', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('GA', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('TN', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('FL', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('NC', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('SC', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('VA', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('PR', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('VI', 'dme', 'CGS Administrators', 'DME-C', 'DME Jurisdiction C'),
('CA', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A'),
('NV', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A'),
('HI', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A'),
('AK', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A'),
('WA', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A'),
('OR', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A'),
('ID', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A'),
('MT', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A'),
('ND', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A'),
('SD', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A'),
('WY', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A'),
('UT', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A'),
('AZ', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A'),
('GU', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A'),
('AS', 'dme', 'Noridian Healthcare Solutions', 'DME-A', 'DME Jurisdiction A')
ON CONFLICT (state_code, jurisdiction_type) DO NOTHING;
