/**
 * Escalation Override Service
 *
 * P5-1 + P5-2: Provides structured justification for clinician overrides
 * and appeal analysis when clinicians disagree with AI escalation levels.
 *
 * When a clinician overrides an AI escalation:
 * - Claude generates structured questions to force reasoning
 * - The justification is documented for audit trail
 * - Override patterns are tracked for AI model improvement
 *
 * When a clinician appeals (escalation too low):
 * - Claude reviews the evidence and existing signals
 * - Generates a recommendation with reasoning
 * - Documents the appeal for audit
 *
 * Tracker: docs/trackers/claude-in-claude-triage-tracker.md (P5-1, P5-2)
 * Copyright © 2025-2026 Envision Virtual Edge Group LLC. All rights reserved.
 */

import { supabase } from '../../lib/supabaseClient';
import type { ServiceResult } from '../_base';
import { success, failure } from '../_base';
import { auditLogger } from '../auditLogger';

// ============================================================================
// Types
// ============================================================================

/** Escalation levels matching the unified enum */
type EscalationLevel = 'none' | 'monitor' | 'notify' | 'escalate' | 'emergency';

/** Input for requesting an override justification */
export interface OverrideRequest {
  patient_id: string;
  tenant_id: string;
  clinician_id: string;
  /** Which AI skill's decision is being overridden */
  skill_key: string;
  /** Original AI-recommended level */
  original_level: EscalationLevel;
  /** Clinician's chosen level */
  override_level: EscalationLevel;
  /** Clinician's stated reason (free-text) */
  clinician_reason: string;
  /** Supporting evidence from the clinician */
  supporting_evidence?: string[];
}

/** Structured justification generated by Claude */
export interface OverrideJustification {
  /** Whether the override is clinically supportable */
  is_justified: boolean;
  /** Structured rationale */
  rationale: string;
  /** Risk assessment of the override */
  risk_assessment: 'low' | 'moderate' | 'high';
  /** What could go wrong if the override is incorrect */
  risk_if_wrong: string;
  /** Recommended monitoring actions */
  monitoring_recommendations: string[];
  /** Follow-up timeframe */
  reassess_in: string;
  /** Structured questions Claude suggests for the clinician */
  clarifying_questions: string[];
  /** Whether this override should be flagged for supervisor review */
  requires_supervisor_review: boolean;
}

/** Input for an appeal (clinician thinks AI escalation is too low) */
export interface AppealRequest {
  patient_id: string;
  tenant_id: string;
  clinician_id: string;
  /** Which AI skill is being appealed */
  skill_key: string;
  /** Current AI-recommended level (too low, per clinician) */
  current_level: EscalationLevel;
  /** Level the clinician believes is appropriate */
  requested_level: EscalationLevel;
  /** Why the clinician disagrees with the AI */
  appeal_reason: string;
  /** Clinical evidence supporting the appeal */
  clinical_evidence: string[];
}

/** Appeal analysis from Claude */
export interface AppealAnalysis {
  /** Whether Claude agrees with the appeal after reviewing evidence */
  appeal_supported: boolean;
  /** Recommended level after analysis */
  recommended_level: EscalationLevel;
  /** Confidence in the recommendation */
  confidence: number;
  /** Detailed reasoning */
  reasoning: string;
  /** Evidence that supports the appeal */
  supporting_factors: string[];
  /** Evidence against the appeal */
  counter_factors: string[];
  /** What the clinician noticed that the AI missed */
  ai_blind_spots: string[];
  /** Whether this represents a systematic AI weakness */
  systematic_issue: boolean;
}

// ============================================================================
// Service
// ============================================================================

export const EscalationOverrideService = {
  /**
   * Generate a structured justification for a clinician's override.
   *
   * When a clinician overrides an AI escalation decision, this method:
   * 1. Sends the override context to Claude for analysis
   * 2. Generates a structured justification with risk assessment
   * 3. Suggests clarifying questions if the reasoning is incomplete
   * 4. Flags high-risk overrides for supervisor review
   *
   * This does NOT block the override — it documents it.
   */
  async generateJustification(
    request: OverrideRequest
  ): Promise<ServiceResult<OverrideJustification>> {
    try {
      if (!request.clinician_reason || request.clinician_reason.trim().length < 10) {
        return failure(
          'INVALID_INPUT',
          'Override reason must be at least 10 characters to ensure adequate documentation'
        );
      }

      await auditLogger.info('ESCALATION_OVERRIDE_JUSTIFICATION_START', {
        patientId: request.patient_id,
        clinicianId: request.clinician_id,
        skillKey: request.skill_key,
        originalLevel: request.original_level,
        overrideLevel: request.override_level,
      });

      const { data, error } = await supabase.functions.invoke('mcp-claude-server', {
        body: {
          method: 'tools/call',
          params: {
            name: 'analyze-text',
            arguments: {
              text: JSON.stringify({
                task: 'escalation_override_justification',
                patient_id: request.patient_id,
                skill_key: request.skill_key,
                original_level: request.original_level,
                override_level: request.override_level,
                clinician_reason: request.clinician_reason,
                supporting_evidence: request.supporting_evidence ?? [],
                response_schema: 'OverrideJustification',
              }),
              analysis_type: 'clinical_override_assessment',
            },
          },
          id: crypto.randomUUID(),
        },
      });

      if (error) {
        return failure('META_TRIAGE_FAILED', `Override justification call failed: ${error.message}`);
      }

      const mcpResponse = data as { result?: { content?: Array<{ text?: string }> } };
      const resultText = mcpResponse?.result?.content?.[0]?.text;
      if (!resultText) {
        return failure('META_TRIAGE_EMPTY', 'Override justification returned empty result');
      }

      const justification = JSON.parse(resultText) as OverrideJustification;

      await auditLogger.info('ESCALATION_OVERRIDE_JUSTIFICATION_COMPLETE', {
        patientId: request.patient_id,
        clinicianId: request.clinician_id,
        isJustified: justification.is_justified,
        riskAssessment: justification.risk_assessment,
        requiresSupervisor: justification.requires_supervisor_review,
      });

      return success(justification);
    } catch (err: unknown) {
      await auditLogger.error(
        'ESCALATION_OVERRIDE_JUSTIFICATION_FAILED',
        err instanceof Error ? err : new Error(String(err)),
        { patientId: request.patient_id, clinicianId: request.clinician_id }
      );
      return failure('AGGREGATION_FAILED', 'Failed to generate override justification');
    }
  },

  /**
   * Analyze an appeal where a clinician believes AI escalation is too low.
   *
   * Reviews the clinical evidence provided by the clinician against the
   * AI's original assessment. Identifies what the AI may have missed
   * (blind spots) and whether this is a systematic issue.
   */
  async analyzeAppeal(
    request: AppealRequest
  ): Promise<ServiceResult<AppealAnalysis>> {
    try {
      if (request.clinical_evidence.length === 0) {
        return failure(
          'INVALID_INPUT',
          'Appeal must include at least one piece of clinical evidence'
        );
      }

      await auditLogger.info('ESCALATION_APPEAL_START', {
        patientId: request.patient_id,
        clinicianId: request.clinician_id,
        skillKey: request.skill_key,
        currentLevel: request.current_level,
        requestedLevel: request.requested_level,
      });

      const { data, error } = await supabase.functions.invoke('mcp-claude-server', {
        body: {
          method: 'tools/call',
          params: {
            name: 'analyze-text',
            arguments: {
              text: JSON.stringify({
                task: 'escalation_appeal_analysis',
                patient_id: request.patient_id,
                skill_key: request.skill_key,
                current_level: request.current_level,
                requested_level: request.requested_level,
                appeal_reason: request.appeal_reason,
                clinical_evidence: request.clinical_evidence,
                response_schema: 'AppealAnalysis',
              }),
              analysis_type: 'clinical_appeal_review',
            },
          },
          id: crypto.randomUUID(),
        },
      });

      if (error) {
        return failure('META_TRIAGE_FAILED', `Appeal analysis call failed: ${error.message}`);
      }

      const mcpResponse = data as { result?: { content?: Array<{ text?: string }> } };
      const resultText = mcpResponse?.result?.content?.[0]?.text;
      if (!resultText) {
        return failure('META_TRIAGE_EMPTY', 'Appeal analysis returned empty result');
      }

      const analysis = JSON.parse(resultText) as AppealAnalysis;

      await auditLogger.info('ESCALATION_APPEAL_COMPLETE', {
        patientId: request.patient_id,
        clinicianId: request.clinician_id,
        appealSupported: analysis.appeal_supported,
        recommendedLevel: analysis.recommended_level,
        confidence: analysis.confidence,
        systematicIssue: analysis.systematic_issue,
        aiBlindSpots: analysis.ai_blind_spots.length,
      });

      return success(analysis);
    } catch (err: unknown) {
      await auditLogger.error(
        'ESCALATION_APPEAL_FAILED',
        err instanceof Error ? err : new Error(String(err)),
        { patientId: request.patient_id, clinicianId: request.clinician_id }
      );
      return failure('AGGREGATION_FAILED', 'Failed to analyze appeal');
    }
  },
};
